/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SegmentacaoRouteImport } from './routes/segmentacao'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as IndexRouteImport } from './routes/index'

const SegmentacaoRoute = SegmentacaoRouteImport.update({
  id: '/segmentacao',
  path: '/segmentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pedidos': typeof PedidosRoute
  '/segmentacao': typeof SegmentacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pedidos': typeof PedidosRoute
  '/segmentacao': typeof SegmentacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pedidos': typeof PedidosRoute
  '/segmentacao': typeof SegmentacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pedidos' | '/segmentacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pedidos' | '/segmentacao'
  id: '__root__' | '/' | '/pedidos' | '/segmentacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PedidosRoute: typeof PedidosRoute
  SegmentacaoRoute: typeof SegmentacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/segmentacao': {
      id: '/segmentacao'
      path: '/segmentacao'
      fullPath: '/segmentacao'
      preLoaderRoute: typeof SegmentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PedidosRoute: PedidosRoute,
  SegmentacaoRoute: SegmentacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
