/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvGeralRouteImport } from './routes/tv-geral'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedOrcamentosRouteImport } from './routes/_authenticated/orcamentos'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedDashboardsRouteImport } from './routes/_authenticated/dashboards'
import { Route as AuthenticatedCuponsRouteImport } from './routes/_authenticated/cupons'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAtlasRouteImport } from './routes/_authenticated/atlas'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedMarketingIndexRouteImport } from './routes/_authenticated/marketing.index'
import { Route as AuthenticatedCarregadoresIndexRouteImport } from './routes/_authenticated/carregadores.index'
import { Route as AuthenticatedMarketingTrafegoRouteImport } from './routes/_authenticated/marketing.trafego'
import { Route as AuthenticatedMarketingSocialRouteImport } from './routes/_authenticated/marketing.social'
import { Route as AuthenticatedMarketingPreVendasRouteImport } from './routes/_authenticated/marketing.pre-vendas'
import { Route as AuthenticatedMarketingMetasRouteImport } from './routes/_authenticated/marketing.metas'
import { Route as AuthenticatedMarketingGargaloRouteImport } from './routes/_authenticated/marketing.gargalo'
import { Route as AuthenticatedMarketingCohortRouteImport } from './routes/_authenticated/marketing.cohort'
import { Route as AuthenticatedMarketingCacRouteImport } from './routes/_authenticated/marketing.cac'
import { Route as AuthenticatedDashboardsMetasRouteImport } from './routes/_authenticated/dashboards.metas'
import { Route as AuthenticatedClientesSugestoesRouteImport } from './routes/_authenticated/clientes.sugestoes'
import { Route as AuthenticatedClientesSegmentacaoRouteImport } from './routes/_authenticated/clientes.segmentacao'
import { Route as AuthenticatedClientesRankingRouteImport } from './routes/_authenticated/clientes.ranking'
import { Route as AuthenticatedClientesPerfilRouteImport } from './routes/_authenticated/clientes.perfil'
import { Route as AuthenticatedClientesCadastrosRouteImport } from './routes/_authenticated/clientes.cadastros'
import { Route as AuthenticatedCarregadoresTarefasRouteImport } from './routes/_authenticated/carregadores.tarefas'
import { Route as AuthenticatedCarregadoresRegrasRouteImport } from './routes/_authenticated/carregadores.regras'
import { Route as AuthenticatedCarregadoresPropostasRouteImport } from './routes/_authenticated/carregadores.propostas'
import { Route as AuthenticatedCarregadoresProdutosRouteImport } from './routes/_authenticated/carregadores.produtos'
import { Route as AuthenticatedCarregadoresPedidosRouteImport } from './routes/_authenticated/carregadores.pedidos'
import { Route as AuthenticatedCarregadoresComissoesRouteImport } from './routes/_authenticated/carregadores.comissoes'
import { Route as AuthenticatedCarregadoresClientesRouteImport } from './routes/_authenticated/carregadores.clientes'
import { Route as AuthenticatedAdminVinculosRouteImport } from './routes/_authenticated/admin.vinculos'
import { Route as AuthenticatedAdminTabelasRouteImport } from './routes/_authenticated/admin.tabelas'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin.produtos'
import { Route as AuthenticatedAdminPermissoesRouteImport } from './routes/_authenticated/admin.permissoes'
import { Route as AuthenticatedAdminPerfisRouteImport } from './routes/_authenticated/admin.perfis'
import { Route as AuthenticatedAdminMetasRouteImport } from './routes/_authenticated/admin.metas'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin.auditoria'
import { Route as AuthenticatedAdminAtividadeRouteImport } from './routes/_authenticated/admin.atividade'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedCarregadoresPropostasIndexRouteImport } from './routes/_authenticated/carregadores.propostas.index'
import { Route as AuthenticatedCarregadoresClientesIndexRouteImport } from './routes/_authenticated/carregadores.clientes.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedCarregadoresPropostasNovaRouteImport } from './routes/_authenticated/carregadores.propostas.nova'
import { Route as AuthenticatedCarregadoresPropostasAuditoriaRouteImport } from './routes/_authenticated/carregadores.propostas.auditoria'
import { Route as AuthenticatedCarregadoresClientesCadastrosRouteImport } from './routes/_authenticated/carregadores.clientes.cadastros'

const TvGeralRoute = TvGeralRouteImport.update({
  id: '/tv-geral',
  path: '/tv-geral',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentosRoute = AuthenticatedOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardsRoute = AuthenticatedDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCuponsRoute = AuthenticatedCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtlasRoute = AuthenticatedAtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMarketingIndexRoute =
  AuthenticatedMarketingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedCarregadoresIndexRoute =
  AuthenticatedCarregadoresIndexRouteImport.update({
    id: '/carregadores/',
    path: '/carregadores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingTrafegoRoute =
  AuthenticatedMarketingTrafegoRouteImport.update({
    id: '/trafego',
    path: '/trafego',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingSocialRoute =
  AuthenticatedMarketingSocialRouteImport.update({
    id: '/social',
    path: '/social',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingPreVendasRoute =
  AuthenticatedMarketingPreVendasRouteImport.update({
    id: '/pre-vendas',
    path: '/pre-vendas',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingMetasRoute =
  AuthenticatedMarketingMetasRouteImport.update({
    id: '/metas',
    path: '/metas',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingGargaloRoute =
  AuthenticatedMarketingGargaloRouteImport.update({
    id: '/gargalo',
    path: '/gargalo',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingCohortRoute =
  AuthenticatedMarketingCohortRouteImport.update({
    id: '/cohort',
    path: '/cohort',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingCacRoute =
  AuthenticatedMarketingCacRouteImport.update({
    id: '/cac',
    path: '/cac',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedDashboardsMetasRoute =
  AuthenticatedDashboardsMetasRouteImport.update({
    id: '/metas',
    path: '/metas',
    getParentRoute: () => AuthenticatedDashboardsRoute,
  } as any)
const AuthenticatedClientesSugestoesRoute =
  AuthenticatedClientesSugestoesRouteImport.update({
    id: '/sugestoes',
    path: '/sugestoes',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const AuthenticatedClientesSegmentacaoRoute =
  AuthenticatedClientesSegmentacaoRouteImport.update({
    id: '/segmentacao',
    path: '/segmentacao',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const AuthenticatedClientesRankingRoute =
  AuthenticatedClientesRankingRouteImport.update({
    id: '/ranking',
    path: '/ranking',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const AuthenticatedClientesPerfilRoute =
  AuthenticatedClientesPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const AuthenticatedClientesCadastrosRoute =
  AuthenticatedClientesCadastrosRouteImport.update({
    id: '/cadastros',
    path: '/cadastros',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const AuthenticatedCarregadoresTarefasRoute =
  AuthenticatedCarregadoresTarefasRouteImport.update({
    id: '/carregadores/tarefas',
    path: '/carregadores/tarefas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarregadoresRegrasRoute =
  AuthenticatedCarregadoresRegrasRouteImport.update({
    id: '/carregadores/regras',
    path: '/carregadores/regras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarregadoresPropostasRoute =
  AuthenticatedCarregadoresPropostasRouteImport.update({
    id: '/carregadores/propostas',
    path: '/carregadores/propostas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarregadoresProdutosRoute =
  AuthenticatedCarregadoresProdutosRouteImport.update({
    id: '/carregadores/produtos',
    path: '/carregadores/produtos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarregadoresPedidosRoute =
  AuthenticatedCarregadoresPedidosRouteImport.update({
    id: '/carregadores/pedidos',
    path: '/carregadores/pedidos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarregadoresComissoesRoute =
  AuthenticatedCarregadoresComissoesRouteImport.update({
    id: '/carregadores/comissoes',
    path: '/carregadores/comissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarregadoresClientesRoute =
  AuthenticatedCarregadoresClientesRouteImport.update({
    id: '/carregadores/clientes',
    path: '/carregadores/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVinculosRoute =
  AuthenticatedAdminVinculosRouteImport.update({
    id: '/admin/vinculos',
    path: '/admin/vinculos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTabelasRoute =
  AuthenticatedAdminTabelasRouteImport.update({
    id: '/admin/tabelas',
    path: '/admin/tabelas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/admin/produtos',
    path: '/admin/produtos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPermissoesRoute =
  AuthenticatedAdminPermissoesRouteImport.update({
    id: '/admin/permissoes',
    path: '/admin/permissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPerfisRoute =
  AuthenticatedAdminPerfisRouteImport.update({
    id: '/admin/perfis',
    path: '/admin/perfis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMetasRoute = AuthenticatedAdminMetasRouteImport.update({
  id: '/admin/metas',
  path: '/admin/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/admin/auditoria',
    path: '/admin/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAtividadeRoute =
  AuthenticatedAdminAtividadeRouteImport.update({
    id: '/admin/atividade',
    path: '/admin/atividade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCarregadoresPropostasIndexRoute =
  AuthenticatedCarregadoresPropostasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCarregadoresPropostasRoute,
  } as any)
const AuthenticatedCarregadoresClientesIndexRoute =
  AuthenticatedCarregadoresClientesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCarregadoresClientesRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCarregadoresPropostasNovaRoute =
  AuthenticatedCarregadoresPropostasNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedCarregadoresPropostasRoute,
  } as any)
const AuthenticatedCarregadoresPropostasAuditoriaRoute =
  AuthenticatedCarregadoresPropostasAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedCarregadoresPropostasRoute,
  } as any)
const AuthenticatedCarregadoresClientesCadastrosRoute =
  AuthenticatedCarregadoresClientesCadastrosRouteImport.update({
    id: '/cadastros',
    path: '/cadastros',
    getParentRoute: () => AuthenticatedCarregadoresClientesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tv-geral': typeof TvGeralRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/atlas': typeof AuthenticatedAtlasRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/cupons': typeof AuthenticatedCuponsRoute
  '/dashboards': typeof AuthenticatedDashboardsRouteWithChildren
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/marketing': typeof AuthenticatedMarketingRouteWithChildren
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/atividade': typeof AuthenticatedAdminAtividadeRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/metas': typeof AuthenticatedAdminMetasRoute
  '/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/tabelas': typeof AuthenticatedAdminTabelasRoute
  '/admin/vinculos': typeof AuthenticatedAdminVinculosRoute
  '/carregadores/clientes': typeof AuthenticatedCarregadoresClientesRouteWithChildren
  '/carregadores/comissoes': typeof AuthenticatedCarregadoresComissoesRoute
  '/carregadores/pedidos': typeof AuthenticatedCarregadoresPedidosRoute
  '/carregadores/produtos': typeof AuthenticatedCarregadoresProdutosRoute
  '/carregadores/propostas': typeof AuthenticatedCarregadoresPropostasRouteWithChildren
  '/carregadores/regras': typeof AuthenticatedCarregadoresRegrasRoute
  '/carregadores/tarefas': typeof AuthenticatedCarregadoresTarefasRoute
  '/clientes/cadastros': typeof AuthenticatedClientesCadastrosRoute
  '/clientes/perfil': typeof AuthenticatedClientesPerfilRoute
  '/clientes/ranking': typeof AuthenticatedClientesRankingRoute
  '/clientes/segmentacao': typeof AuthenticatedClientesSegmentacaoRoute
  '/clientes/sugestoes': typeof AuthenticatedClientesSugestoesRoute
  '/dashboards/metas': typeof AuthenticatedDashboardsMetasRoute
  '/marketing/cac': typeof AuthenticatedMarketingCacRoute
  '/marketing/cohort': typeof AuthenticatedMarketingCohortRoute
  '/marketing/gargalo': typeof AuthenticatedMarketingGargaloRoute
  '/marketing/metas': typeof AuthenticatedMarketingMetasRoute
  '/marketing/pre-vendas': typeof AuthenticatedMarketingPreVendasRoute
  '/marketing/social': typeof AuthenticatedMarketingSocialRoute
  '/marketing/trafego': typeof AuthenticatedMarketingTrafegoRoute
  '/carregadores/': typeof AuthenticatedCarregadoresIndexRoute
  '/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/carregadores/clientes/cadastros': typeof AuthenticatedCarregadoresClientesCadastrosRoute
  '/carregadores/propostas/auditoria': typeof AuthenticatedCarregadoresPropostasAuditoriaRoute
  '/carregadores/propostas/nova': typeof AuthenticatedCarregadoresPropostasNovaRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/carregadores/clientes/': typeof AuthenticatedCarregadoresClientesIndexRoute
  '/carregadores/propostas/': typeof AuthenticatedCarregadoresPropostasIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tv-geral': typeof TvGeralRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/atlas': typeof AuthenticatedAtlasRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/cupons': typeof AuthenticatedCuponsRoute
  '/dashboards': typeof AuthenticatedDashboardsRouteWithChildren
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/atividade': typeof AuthenticatedAdminAtividadeRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/metas': typeof AuthenticatedAdminMetasRoute
  '/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/tabelas': typeof AuthenticatedAdminTabelasRoute
  '/admin/vinculos': typeof AuthenticatedAdminVinculosRoute
  '/carregadores/comissoes': typeof AuthenticatedCarregadoresComissoesRoute
  '/carregadores/pedidos': typeof AuthenticatedCarregadoresPedidosRoute
  '/carregadores/produtos': typeof AuthenticatedCarregadoresProdutosRoute
  '/carregadores/regras': typeof AuthenticatedCarregadoresRegrasRoute
  '/carregadores/tarefas': typeof AuthenticatedCarregadoresTarefasRoute
  '/clientes/cadastros': typeof AuthenticatedClientesCadastrosRoute
  '/clientes/perfil': typeof AuthenticatedClientesPerfilRoute
  '/clientes/ranking': typeof AuthenticatedClientesRankingRoute
  '/clientes/segmentacao': typeof AuthenticatedClientesSegmentacaoRoute
  '/clientes/sugestoes': typeof AuthenticatedClientesSugestoesRoute
  '/dashboards/metas': typeof AuthenticatedDashboardsMetasRoute
  '/marketing/cac': typeof AuthenticatedMarketingCacRoute
  '/marketing/cohort': typeof AuthenticatedMarketingCohortRoute
  '/marketing/gargalo': typeof AuthenticatedMarketingGargaloRoute
  '/marketing/metas': typeof AuthenticatedMarketingMetasRoute
  '/marketing/pre-vendas': typeof AuthenticatedMarketingPreVendasRoute
  '/marketing/social': typeof AuthenticatedMarketingSocialRoute
  '/marketing/trafego': typeof AuthenticatedMarketingTrafegoRoute
  '/carregadores': typeof AuthenticatedCarregadoresIndexRoute
  '/marketing': typeof AuthenticatedMarketingIndexRoute
  '/carregadores/clientes/cadastros': typeof AuthenticatedCarregadoresClientesCadastrosRoute
  '/carregadores/propostas/auditoria': typeof AuthenticatedCarregadoresPropostasAuditoriaRoute
  '/carregadores/propostas/nova': typeof AuthenticatedCarregadoresPropostasNovaRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/carregadores/clientes': typeof AuthenticatedCarregadoresClientesIndexRoute
  '/carregadores/propostas': typeof AuthenticatedCarregadoresPropostasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tv-geral': typeof TvGeralRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/atlas': typeof AuthenticatedAtlasRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/cupons': typeof AuthenticatedCuponsRoute
  '/_authenticated/dashboards': typeof AuthenticatedDashboardsRouteWithChildren
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRouteWithChildren
  '/_authenticated/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/atividade': typeof AuthenticatedAdminAtividadeRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/metas': typeof AuthenticatedAdminMetasRoute
  '/_authenticated/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/_authenticated/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/_authenticated/admin/tabelas': typeof AuthenticatedAdminTabelasRoute
  '/_authenticated/admin/vinculos': typeof AuthenticatedAdminVinculosRoute
  '/_authenticated/carregadores/clientes': typeof AuthenticatedCarregadoresClientesRouteWithChildren
  '/_authenticated/carregadores/comissoes': typeof AuthenticatedCarregadoresComissoesRoute
  '/_authenticated/carregadores/pedidos': typeof AuthenticatedCarregadoresPedidosRoute
  '/_authenticated/carregadores/produtos': typeof AuthenticatedCarregadoresProdutosRoute
  '/_authenticated/carregadores/propostas': typeof AuthenticatedCarregadoresPropostasRouteWithChildren
  '/_authenticated/carregadores/regras': typeof AuthenticatedCarregadoresRegrasRoute
  '/_authenticated/carregadores/tarefas': typeof AuthenticatedCarregadoresTarefasRoute
  '/_authenticated/clientes/cadastros': typeof AuthenticatedClientesCadastrosRoute
  '/_authenticated/clientes/perfil': typeof AuthenticatedClientesPerfilRoute
  '/_authenticated/clientes/ranking': typeof AuthenticatedClientesRankingRoute
  '/_authenticated/clientes/segmentacao': typeof AuthenticatedClientesSegmentacaoRoute
  '/_authenticated/clientes/sugestoes': typeof AuthenticatedClientesSugestoesRoute
  '/_authenticated/dashboards/metas': typeof AuthenticatedDashboardsMetasRoute
  '/_authenticated/marketing/cac': typeof AuthenticatedMarketingCacRoute
  '/_authenticated/marketing/cohort': typeof AuthenticatedMarketingCohortRoute
  '/_authenticated/marketing/gargalo': typeof AuthenticatedMarketingGargaloRoute
  '/_authenticated/marketing/metas': typeof AuthenticatedMarketingMetasRoute
  '/_authenticated/marketing/pre-vendas': typeof AuthenticatedMarketingPreVendasRoute
  '/_authenticated/marketing/social': typeof AuthenticatedMarketingSocialRoute
  '/_authenticated/marketing/trafego': typeof AuthenticatedMarketingTrafegoRoute
  '/_authenticated/carregadores/': typeof AuthenticatedCarregadoresIndexRoute
  '/_authenticated/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/_authenticated/carregadores/clientes/cadastros': typeof AuthenticatedCarregadoresClientesCadastrosRoute
  '/_authenticated/carregadores/propostas/auditoria': typeof AuthenticatedCarregadoresPropostasAuditoriaRoute
  '/_authenticated/carregadores/propostas/nova': typeof AuthenticatedCarregadoresPropostasNovaRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/carregadores/clientes/': typeof AuthenticatedCarregadoresClientesIndexRoute
  '/_authenticated/carregadores/propostas/': typeof AuthenticatedCarregadoresPropostasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tv-geral'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/atlas'
    | '/clientes'
    | '/cupons'
    | '/dashboards'
    | '/integracoes'
    | '/marketing'
    | '/orcamentos'
    | '/pedidos'
    | '/perfil'
    | '/tarefas'
    | '/usuarios'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/atividade'
    | '/admin/auditoria'
    | '/admin/metas'
    | '/admin/perfis'
    | '/admin/permissoes'
    | '/admin/produtos'
    | '/admin/tabelas'
    | '/admin/vinculos'
    | '/carregadores/clientes'
    | '/carregadores/comissoes'
    | '/carregadores/pedidos'
    | '/carregadores/produtos'
    | '/carregadores/propostas'
    | '/carregadores/regras'
    | '/carregadores/tarefas'
    | '/clientes/cadastros'
    | '/clientes/perfil'
    | '/clientes/ranking'
    | '/clientes/segmentacao'
    | '/clientes/sugestoes'
    | '/dashboards/metas'
    | '/marketing/cac'
    | '/marketing/cohort'
    | '/marketing/gargalo'
    | '/marketing/metas'
    | '/marketing/pre-vendas'
    | '/marketing/social'
    | '/marketing/trafego'
    | '/carregadores/'
    | '/marketing/'
    | '/carregadores/clientes/cadastros'
    | '/carregadores/propostas/auditoria'
    | '/carregadores/propostas/nova'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/carregadores/clientes/'
    | '/carregadores/propostas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tv-geral'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/atlas'
    | '/clientes'
    | '/cupons'
    | '/dashboards'
    | '/integracoes'
    | '/orcamentos'
    | '/pedidos'
    | '/perfil'
    | '/tarefas'
    | '/usuarios'
    | '/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/atividade'
    | '/admin/auditoria'
    | '/admin/metas'
    | '/admin/perfis'
    | '/admin/permissoes'
    | '/admin/produtos'
    | '/admin/tabelas'
    | '/admin/vinculos'
    | '/carregadores/comissoes'
    | '/carregadores/pedidos'
    | '/carregadores/produtos'
    | '/carregadores/regras'
    | '/carregadores/tarefas'
    | '/clientes/cadastros'
    | '/clientes/perfil'
    | '/clientes/ranking'
    | '/clientes/segmentacao'
    | '/clientes/sugestoes'
    | '/dashboards/metas'
    | '/marketing/cac'
    | '/marketing/cohort'
    | '/marketing/gargalo'
    | '/marketing/metas'
    | '/marketing/pre-vendas'
    | '/marketing/social'
    | '/marketing/trafego'
    | '/carregadores'
    | '/marketing'
    | '/carregadores/clientes/cadastros'
    | '/carregadores/propostas/auditoria'
    | '/carregadores/propostas/nova'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/carregadores/clientes'
    | '/carregadores/propostas'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tv-geral'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/atlas'
    | '/_authenticated/clientes'
    | '/_authenticated/cupons'
    | '/_authenticated/dashboards'
    | '/_authenticated/integracoes'
    | '/_authenticated/marketing'
    | '/_authenticated/orcamentos'
    | '/_authenticated/pedidos'
    | '/_authenticated/perfil'
    | '/_authenticated/tarefas'
    | '/_authenticated/usuarios'
    | '/_authenticated/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/atividade'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/metas'
    | '/_authenticated/admin/perfis'
    | '/_authenticated/admin/permissoes'
    | '/_authenticated/admin/produtos'
    | '/_authenticated/admin/tabelas'
    | '/_authenticated/admin/vinculos'
    | '/_authenticated/carregadores/clientes'
    | '/_authenticated/carregadores/comissoes'
    | '/_authenticated/carregadores/pedidos'
    | '/_authenticated/carregadores/produtos'
    | '/_authenticated/carregadores/propostas'
    | '/_authenticated/carregadores/regras'
    | '/_authenticated/carregadores/tarefas'
    | '/_authenticated/clientes/cadastros'
    | '/_authenticated/clientes/perfil'
    | '/_authenticated/clientes/ranking'
    | '/_authenticated/clientes/segmentacao'
    | '/_authenticated/clientes/sugestoes'
    | '/_authenticated/dashboards/metas'
    | '/_authenticated/marketing/cac'
    | '/_authenticated/marketing/cohort'
    | '/_authenticated/marketing/gargalo'
    | '/_authenticated/marketing/metas'
    | '/_authenticated/marketing/pre-vendas'
    | '/_authenticated/marketing/social'
    | '/_authenticated/marketing/trafego'
    | '/_authenticated/carregadores/'
    | '/_authenticated/marketing/'
    | '/_authenticated/carregadores/clientes/cadastros'
    | '/_authenticated/carregadores/propostas/auditoria'
    | '/_authenticated/carregadores/propostas/nova'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/carregadores/clientes/'
    | '/_authenticated/carregadores/propostas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TvGeralRoute: typeof TvGeralRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv-geral': {
      id: '/tv-geral'
      path: '/tv-geral'
      fullPath: '/tv-geral'
      preLoaderRoute: typeof TvGeralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos': {
      id: '/_authenticated/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AuthenticatedOrcamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboards': {
      id: '/_authenticated/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AuthenticatedDashboardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cupons': {
      id: '/_authenticated/cupons'
      path: '/cupons'
      fullPath: '/cupons'
      preLoaderRoute: typeof AuthenticatedCuponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atlas': {
      id: '/_authenticated/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AuthenticatedAtlasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/marketing/': {
      id: '/_authenticated/marketing/'
      path: '/'
      fullPath: '/marketing/'
      preLoaderRoute: typeof AuthenticatedMarketingIndexRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/carregadores/': {
      id: '/_authenticated/carregadores/'
      path: '/carregadores'
      fullPath: '/carregadores/'
      preLoaderRoute: typeof AuthenticatedCarregadoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing/trafego': {
      id: '/_authenticated/marketing/trafego'
      path: '/trafego'
      fullPath: '/marketing/trafego'
      preLoaderRoute: typeof AuthenticatedMarketingTrafegoRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/social': {
      id: '/_authenticated/marketing/social'
      path: '/social'
      fullPath: '/marketing/social'
      preLoaderRoute: typeof AuthenticatedMarketingSocialRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/pre-vendas': {
      id: '/_authenticated/marketing/pre-vendas'
      path: '/pre-vendas'
      fullPath: '/marketing/pre-vendas'
      preLoaderRoute: typeof AuthenticatedMarketingPreVendasRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/metas': {
      id: '/_authenticated/marketing/metas'
      path: '/metas'
      fullPath: '/marketing/metas'
      preLoaderRoute: typeof AuthenticatedMarketingMetasRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/gargalo': {
      id: '/_authenticated/marketing/gargalo'
      path: '/gargalo'
      fullPath: '/marketing/gargalo'
      preLoaderRoute: typeof AuthenticatedMarketingGargaloRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/cohort': {
      id: '/_authenticated/marketing/cohort'
      path: '/cohort'
      fullPath: '/marketing/cohort'
      preLoaderRoute: typeof AuthenticatedMarketingCohortRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/cac': {
      id: '/_authenticated/marketing/cac'
      path: '/cac'
      fullPath: '/marketing/cac'
      preLoaderRoute: typeof AuthenticatedMarketingCacRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/dashboards/metas': {
      id: '/_authenticated/dashboards/metas'
      path: '/metas'
      fullPath: '/dashboards/metas'
      preLoaderRoute: typeof AuthenticatedDashboardsMetasRouteImport
      parentRoute: typeof AuthenticatedDashboardsRoute
    }
    '/_authenticated/clientes/sugestoes': {
      id: '/_authenticated/clientes/sugestoes'
      path: '/sugestoes'
      fullPath: '/clientes/sugestoes'
      preLoaderRoute: typeof AuthenticatedClientesSugestoesRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/clientes/segmentacao': {
      id: '/_authenticated/clientes/segmentacao'
      path: '/segmentacao'
      fullPath: '/clientes/segmentacao'
      preLoaderRoute: typeof AuthenticatedClientesSegmentacaoRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/clientes/ranking': {
      id: '/_authenticated/clientes/ranking'
      path: '/ranking'
      fullPath: '/clientes/ranking'
      preLoaderRoute: typeof AuthenticatedClientesRankingRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/clientes/perfil': {
      id: '/_authenticated/clientes/perfil'
      path: '/perfil'
      fullPath: '/clientes/perfil'
      preLoaderRoute: typeof AuthenticatedClientesPerfilRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/clientes/cadastros': {
      id: '/_authenticated/clientes/cadastros'
      path: '/cadastros'
      fullPath: '/clientes/cadastros'
      preLoaderRoute: typeof AuthenticatedClientesCadastrosRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/carregadores/tarefas': {
      id: '/_authenticated/carregadores/tarefas'
      path: '/carregadores/tarefas'
      fullPath: '/carregadores/tarefas'
      preLoaderRoute: typeof AuthenticatedCarregadoresTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carregadores/regras': {
      id: '/_authenticated/carregadores/regras'
      path: '/carregadores/regras'
      fullPath: '/carregadores/regras'
      preLoaderRoute: typeof AuthenticatedCarregadoresRegrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carregadores/propostas': {
      id: '/_authenticated/carregadores/propostas'
      path: '/carregadores/propostas'
      fullPath: '/carregadores/propostas'
      preLoaderRoute: typeof AuthenticatedCarregadoresPropostasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carregadores/produtos': {
      id: '/_authenticated/carregadores/produtos'
      path: '/carregadores/produtos'
      fullPath: '/carregadores/produtos'
      preLoaderRoute: typeof AuthenticatedCarregadoresProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carregadores/pedidos': {
      id: '/_authenticated/carregadores/pedidos'
      path: '/carregadores/pedidos'
      fullPath: '/carregadores/pedidos'
      preLoaderRoute: typeof AuthenticatedCarregadoresPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carregadores/comissoes': {
      id: '/_authenticated/carregadores/comissoes'
      path: '/carregadores/comissoes'
      fullPath: '/carregadores/comissoes'
      preLoaderRoute: typeof AuthenticatedCarregadoresComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carregadores/clientes': {
      id: '/_authenticated/carregadores/clientes'
      path: '/carregadores/clientes'
      fullPath: '/carregadores/clientes'
      preLoaderRoute: typeof AuthenticatedCarregadoresClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/vinculos': {
      id: '/_authenticated/admin/vinculos'
      path: '/admin/vinculos'
      fullPath: '/admin/vinculos'
      preLoaderRoute: typeof AuthenticatedAdminVinculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tabelas': {
      id: '/_authenticated/admin/tabelas'
      path: '/admin/tabelas'
      fullPath: '/admin/tabelas'
      preLoaderRoute: typeof AuthenticatedAdminTabelasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/permissoes': {
      id: '/_authenticated/admin/permissoes'
      path: '/admin/permissoes'
      fullPath: '/admin/permissoes'
      preLoaderRoute: typeof AuthenticatedAdminPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/perfis': {
      id: '/_authenticated/admin/perfis'
      path: '/admin/perfis'
      fullPath: '/admin/perfis'
      preLoaderRoute: typeof AuthenticatedAdminPerfisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/metas': {
      id: '/_authenticated/admin/metas'
      path: '/admin/metas'
      fullPath: '/admin/metas'
      preLoaderRoute: typeof AuthenticatedAdminMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/atividade': {
      id: '/_authenticated/admin/atividade'
      path: '/admin/atividade'
      fullPath: '/admin/atividade'
      preLoaderRoute: typeof AuthenticatedAdminAtividadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/carregadores/propostas/': {
      id: '/_authenticated/carregadores/propostas/'
      path: '/'
      fullPath: '/carregadores/propostas/'
      preLoaderRoute: typeof AuthenticatedCarregadoresPropostasIndexRouteImport
      parentRoute: typeof AuthenticatedCarregadoresPropostasRoute
    }
    '/_authenticated/carregadores/clientes/': {
      id: '/_authenticated/carregadores/clientes/'
      path: '/'
      fullPath: '/carregadores/clientes/'
      preLoaderRoute: typeof AuthenticatedCarregadoresClientesIndexRouteImport
      parentRoute: typeof AuthenticatedCarregadoresClientesRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/carregadores/propostas/nova': {
      id: '/_authenticated/carregadores/propostas/nova'
      path: '/nova'
      fullPath: '/carregadores/propostas/nova'
      preLoaderRoute: typeof AuthenticatedCarregadoresPropostasNovaRouteImport
      parentRoute: typeof AuthenticatedCarregadoresPropostasRoute
    }
    '/_authenticated/carregadores/propostas/auditoria': {
      id: '/_authenticated/carregadores/propostas/auditoria'
      path: '/auditoria'
      fullPath: '/carregadores/propostas/auditoria'
      preLoaderRoute: typeof AuthenticatedCarregadoresPropostasAuditoriaRouteImport
      parentRoute: typeof AuthenticatedCarregadoresPropostasRoute
    }
    '/_authenticated/carregadores/clientes/cadastros': {
      id: '/_authenticated/carregadores/clientes/cadastros'
      path: '/cadastros'
      fullPath: '/carregadores/clientes/cadastros'
      preLoaderRoute: typeof AuthenticatedCarregadoresClientesCadastrosRouteImport
      parentRoute: typeof AuthenticatedCarregadoresClientesRoute
    }
  }
}

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesCadastrosRoute: typeof AuthenticatedClientesCadastrosRoute
  AuthenticatedClientesPerfilRoute: typeof AuthenticatedClientesPerfilRoute
  AuthenticatedClientesRankingRoute: typeof AuthenticatedClientesRankingRoute
  AuthenticatedClientesSegmentacaoRoute: typeof AuthenticatedClientesSegmentacaoRoute
  AuthenticatedClientesSugestoesRoute: typeof AuthenticatedClientesSugestoesRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesCadastrosRoute: AuthenticatedClientesCadastrosRoute,
  AuthenticatedClientesPerfilRoute: AuthenticatedClientesPerfilRoute,
  AuthenticatedClientesRankingRoute: AuthenticatedClientesRankingRoute,
  AuthenticatedClientesSegmentacaoRoute: AuthenticatedClientesSegmentacaoRoute,
  AuthenticatedClientesSugestoesRoute: AuthenticatedClientesSugestoesRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedDashboardsRouteChildren {
  AuthenticatedDashboardsMetasRoute: typeof AuthenticatedDashboardsMetasRoute
}

const AuthenticatedDashboardsRouteChildren: AuthenticatedDashboardsRouteChildren =
  {
    AuthenticatedDashboardsMetasRoute: AuthenticatedDashboardsMetasRoute,
  }

const AuthenticatedDashboardsRouteWithChildren =
  AuthenticatedDashboardsRoute._addFileChildren(
    AuthenticatedDashboardsRouteChildren,
  )

interface AuthenticatedMarketingRouteChildren {
  AuthenticatedMarketingCacRoute: typeof AuthenticatedMarketingCacRoute
  AuthenticatedMarketingCohortRoute: typeof AuthenticatedMarketingCohortRoute
  AuthenticatedMarketingGargaloRoute: typeof AuthenticatedMarketingGargaloRoute
  AuthenticatedMarketingMetasRoute: typeof AuthenticatedMarketingMetasRoute
  AuthenticatedMarketingPreVendasRoute: typeof AuthenticatedMarketingPreVendasRoute
  AuthenticatedMarketingSocialRoute: typeof AuthenticatedMarketingSocialRoute
  AuthenticatedMarketingTrafegoRoute: typeof AuthenticatedMarketingTrafegoRoute
  AuthenticatedMarketingIndexRoute: typeof AuthenticatedMarketingIndexRoute
}

const AuthenticatedMarketingRouteChildren: AuthenticatedMarketingRouteChildren =
  {
    AuthenticatedMarketingCacRoute: AuthenticatedMarketingCacRoute,
    AuthenticatedMarketingCohortRoute: AuthenticatedMarketingCohortRoute,
    AuthenticatedMarketingGargaloRoute: AuthenticatedMarketingGargaloRoute,
    AuthenticatedMarketingMetasRoute: AuthenticatedMarketingMetasRoute,
    AuthenticatedMarketingPreVendasRoute: AuthenticatedMarketingPreVendasRoute,
    AuthenticatedMarketingSocialRoute: AuthenticatedMarketingSocialRoute,
    AuthenticatedMarketingTrafegoRoute: AuthenticatedMarketingTrafegoRoute,
    AuthenticatedMarketingIndexRoute: AuthenticatedMarketingIndexRoute,
  }

const AuthenticatedMarketingRouteWithChildren =
  AuthenticatedMarketingRoute._addFileChildren(
    AuthenticatedMarketingRouteChildren,
  )

interface AuthenticatedCarregadoresClientesRouteChildren {
  AuthenticatedCarregadoresClientesCadastrosRoute: typeof AuthenticatedCarregadoresClientesCadastrosRoute
  AuthenticatedCarregadoresClientesIndexRoute: typeof AuthenticatedCarregadoresClientesIndexRoute
}

const AuthenticatedCarregadoresClientesRouteChildren: AuthenticatedCarregadoresClientesRouteChildren =
  {
    AuthenticatedCarregadoresClientesCadastrosRoute:
      AuthenticatedCarregadoresClientesCadastrosRoute,
    AuthenticatedCarregadoresClientesIndexRoute:
      AuthenticatedCarregadoresClientesIndexRoute,
  }

const AuthenticatedCarregadoresClientesRouteWithChildren =
  AuthenticatedCarregadoresClientesRoute._addFileChildren(
    AuthenticatedCarregadoresClientesRouteChildren,
  )

interface AuthenticatedCarregadoresPropostasRouteChildren {
  AuthenticatedCarregadoresPropostasAuditoriaRoute: typeof AuthenticatedCarregadoresPropostasAuditoriaRoute
  AuthenticatedCarregadoresPropostasNovaRoute: typeof AuthenticatedCarregadoresPropostasNovaRoute
  AuthenticatedCarregadoresPropostasIndexRoute: typeof AuthenticatedCarregadoresPropostasIndexRoute
}

const AuthenticatedCarregadoresPropostasRouteChildren: AuthenticatedCarregadoresPropostasRouteChildren =
  {
    AuthenticatedCarregadoresPropostasAuditoriaRoute:
      AuthenticatedCarregadoresPropostasAuditoriaRoute,
    AuthenticatedCarregadoresPropostasNovaRoute:
      AuthenticatedCarregadoresPropostasNovaRoute,
    AuthenticatedCarregadoresPropostasIndexRoute:
      AuthenticatedCarregadoresPropostasIndexRoute,
  }

const AuthenticatedCarregadoresPropostasRouteWithChildren =
  AuthenticatedCarregadoresPropostasRoute._addFileChildren(
    AuthenticatedCarregadoresPropostasRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtlasRoute: typeof AuthenticatedAtlasRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedCuponsRoute: typeof AuthenticatedCuponsRoute
  AuthenticatedDashboardsRoute: typeof AuthenticatedDashboardsRouteWithChildren
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRouteWithChildren
  AuthenticatedOrcamentosRoute: typeof AuthenticatedOrcamentosRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminAtividadeRoute: typeof AuthenticatedAdminAtividadeRoute
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminMetasRoute: typeof AuthenticatedAdminMetasRoute
  AuthenticatedAdminPerfisRoute: typeof AuthenticatedAdminPerfisRoute
  AuthenticatedAdminPermissoesRoute: typeof AuthenticatedAdminPermissoesRoute
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRoute
  AuthenticatedAdminTabelasRoute: typeof AuthenticatedAdminTabelasRoute
  AuthenticatedAdminVinculosRoute: typeof AuthenticatedAdminVinculosRoute
  AuthenticatedCarregadoresClientesRoute: typeof AuthenticatedCarregadoresClientesRouteWithChildren
  AuthenticatedCarregadoresComissoesRoute: typeof AuthenticatedCarregadoresComissoesRoute
  AuthenticatedCarregadoresPedidosRoute: typeof AuthenticatedCarregadoresPedidosRoute
  AuthenticatedCarregadoresProdutosRoute: typeof AuthenticatedCarregadoresProdutosRoute
  AuthenticatedCarregadoresPropostasRoute: typeof AuthenticatedCarregadoresPropostasRouteWithChildren
  AuthenticatedCarregadoresRegrasRoute: typeof AuthenticatedCarregadoresRegrasRoute
  AuthenticatedCarregadoresTarefasRoute: typeof AuthenticatedCarregadoresTarefasRoute
  AuthenticatedCarregadoresIndexRoute: typeof AuthenticatedCarregadoresIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtlasRoute: AuthenticatedAtlasRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedCuponsRoute: AuthenticatedCuponsRoute,
  AuthenticatedDashboardsRoute: AuthenticatedDashboardsRouteWithChildren,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRouteWithChildren,
  AuthenticatedOrcamentosRoute: AuthenticatedOrcamentosRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminAtividadeRoute: AuthenticatedAdminAtividadeRoute,
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminMetasRoute: AuthenticatedAdminMetasRoute,
  AuthenticatedAdminPerfisRoute: AuthenticatedAdminPerfisRoute,
  AuthenticatedAdminPermissoesRoute: AuthenticatedAdminPermissoesRoute,
  AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRoute,
  AuthenticatedAdminTabelasRoute: AuthenticatedAdminTabelasRoute,
  AuthenticatedAdminVinculosRoute: AuthenticatedAdminVinculosRoute,
  AuthenticatedCarregadoresClientesRoute:
    AuthenticatedCarregadoresClientesRouteWithChildren,
  AuthenticatedCarregadoresComissoesRoute:
    AuthenticatedCarregadoresComissoesRoute,
  AuthenticatedCarregadoresPedidosRoute: AuthenticatedCarregadoresPedidosRoute,
  AuthenticatedCarregadoresProdutosRoute:
    AuthenticatedCarregadoresProdutosRoute,
  AuthenticatedCarregadoresPropostasRoute:
    AuthenticatedCarregadoresPropostasRouteWithChildren,
  AuthenticatedCarregadoresRegrasRoute: AuthenticatedCarregadoresRegrasRoute,
  AuthenticatedCarregadoresTarefasRoute: AuthenticatedCarregadoresTarefasRoute,
  AuthenticatedCarregadoresIndexRoute: AuthenticatedCarregadoresIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TvGeralRoute: TvGeralRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
