/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvGeralRouteImport } from './routes/tv-geral'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedMarketingIndexRouteImport } from './routes/_authenticated/marketing.index'
import { Route as AuthenticatedCarregadoresIndexRouteImport } from './routes/_authenticated/carregadores.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicAppVersionRouteImport } from './routes/api/public/app-version'
import { Route as AuthenticatedSolarTarefasRouteImport } from './routes/_authenticated/solar.tarefas'
import { Route as AuthenticatedSolarPedidosRouteImport } from './routes/_authenticated/solar.pedidos'
import { Route as AuthenticatedSolarDashboardsRouteImport } from './routes/_authenticated/solar.dashboards'
import { Route as AuthenticatedSolarCuponsRouteImport } from './routes/_authenticated/solar.cupons'
import { Route as AuthenticatedSolarClientesRouteImport } from './routes/_authenticated/solar.clientes'
import { Route as AuthenticatedSolarAtlasRouteImport } from './routes/_authenticated/solar.atlas'
import { Route as AuthenticatedMarketingTrafegoRouteImport } from './routes/_authenticated/marketing.trafego'
import { Route as AuthenticatedMarketingSocialRouteImport } from './routes/_authenticated/marketing.social'
import { Route as AuthenticatedMarketingPreVendasRouteImport } from './routes/_authenticated/marketing.pre-vendas'
import { Route as AuthenticatedMarketingMetasRouteImport } from './routes/_authenticated/marketing.metas'
import { Route as AuthenticatedMarketingGargaloRouteImport } from './routes/_authenticated/marketing.gargalo'
import { Route as AuthenticatedMarketingCohortRouteImport } from './routes/_authenticated/marketing.cohort'
import { Route as AuthenticatedMarketingCacRouteImport } from './routes/_authenticated/marketing.cac'
import { Route as AuthenticatedCarregadoresTarefasRouteImport } from './routes/_authenticated/carregadores.tarefas'
import { Route as AuthenticatedCarregadoresRegrasRouteImport } from './routes/_authenticated/carregadores.regras'
import { Route as AuthenticatedCarregadoresPropostasRouteImport } from './routes/_authenticated/carregadores.propostas'
import { Route as AuthenticatedCarregadoresProdutosRouteImport } from './routes/_authenticated/carregadores.produtos'
import { Route as AuthenticatedCarregadoresPedidosRouteImport } from './routes/_authenticated/carregadores.pedidos'
import { Route as AuthenticatedCarregadoresMetasRouteImport } from './routes/_authenticated/carregadores.metas'
import { Route as AuthenticatedCarregadoresFreteRegrasRouteImport } from './routes/_authenticated/carregadores.frete-regras'
import { Route as AuthenticatedCarregadoresComissoesRouteImport } from './routes/_authenticated/carregadores.comissoes'
import { Route as AuthenticatedCarregadoresClientesRouteImport } from './routes/_authenticated/carregadores.clientes'
import { Route as AuthenticatedAdminVinculosRouteImport } from './routes/_authenticated/admin.vinculos'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminTabelasRouteImport } from './routes/_authenticated/admin.tabelas'
import { Route as AuthenticatedAdminRegrasRouteImport } from './routes/_authenticated/admin.regras'
import { Route as AuthenticatedAdminProdutosSolarRouteImport } from './routes/_authenticated/admin.produtos-solar'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin.produtos'
import { Route as AuthenticatedAdminPerfisRouteImport } from './routes/_authenticated/admin.perfis'
import { Route as AuthenticatedAdminModulosSolarRouteImport } from './routes/_authenticated/admin.modulos-solar'
import { Route as AuthenticatedAdminModeracaoRouteImport } from './routes/_authenticated/admin.moderacao'
import { Route as AuthenticatedAdminMetasRouteImport } from './routes/_authenticated/admin.metas'
import { Route as AuthenticatedAdminIntegracoesRouteImport } from './routes/_authenticated/admin.integracoes'
import { Route as AuthenticatedAdminFreteRegrasRouteImport } from './routes/_authenticated/admin.frete-regras'
import { Route as AuthenticatedAdminEstoqueRouteImport } from './routes/_authenticated/admin.estoque'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminComissoesRouteImport } from './routes/_authenticated/admin.comissoes'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin.auditoria'
import { Route as AuthenticatedAdminAtividadeRouteImport } from './routes/_authenticated/admin.atividade'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedSolarPropostasIndexRouteImport } from './routes/_authenticated/solar.propostas.index'
import { Route as AuthenticatedCarregadoresPropostasIndexRouteImport } from './routes/_authenticated/carregadores.propostas.index'
import { Route as AuthenticatedCarregadoresClientesIndexRouteImport } from './routes/_authenticated/carregadores.clientes.index'
import { Route as AuthenticatedAdminLogsIndexRouteImport } from './routes/_authenticated/admin.logs.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksSapNfsRouteImport } from './routes/api/public/hooks/sap-nfs'
import { Route as ApiPublicHooksPixItauRouteImport } from './routes/api/public/hooks/pix-itau'
import { Route as ApiPublicHooksPagamentoLinkRouteImport } from './routes/api/public/hooks/pagamento-link'
import { Route as ApiPublicHooksFretefyTrackingRouteImport } from './routes/api/public/hooks/fretefy-tracking'
import { Route as AuthenticatedSolarPropostasNovaRouteImport } from './routes/_authenticated/solar.propostas.nova'
import { Route as AuthenticatedSolarDashboardsMetasRouteImport } from './routes/_authenticated/solar.dashboards.metas'
import { Route as AuthenticatedSolarClientesSugestoesRouteImport } from './routes/_authenticated/solar.clientes.sugestoes'
import { Route as AuthenticatedSolarClientesSegmentacaoRouteImport } from './routes/_authenticated/solar.clientes.segmentacao'
import { Route as AuthenticatedSolarClientesRankingRouteImport } from './routes/_authenticated/solar.clientes.ranking'
import { Route as AuthenticatedSolarClientesPerfilRouteImport } from './routes/_authenticated/solar.clientes.perfil'
import { Route as AuthenticatedSolarClientesCadastrosRouteImport } from './routes/_authenticated/solar.clientes.cadastros'
import { Route as AuthenticatedCarregadoresPropostasVisualizarRouteImport } from './routes/_authenticated/carregadores.propostas.visualizar'
import { Route as AuthenticatedCarregadoresPropostasNovaRouteImport } from './routes/_authenticated/carregadores.propostas.nova'
import { Route as AuthenticatedCarregadoresPropostasAuditoriaRouteImport } from './routes/_authenticated/carregadores.propostas.auditoria'
import { Route as AuthenticatedCarregadoresClientesCadastrosRouteImport } from './routes/_authenticated/carregadores.clientes.cadastros'
import { Route as AuthenticatedAdminLogsRetencaoRouteImport } from './routes/_authenticated/admin.logs.retencao'
import { Route as AuthenticatedAdminLogsModeracaoRouteImport } from './routes/_authenticated/admin.logs.moderacao'
import { Route as AuthenticatedAdminLogsIntegracoesRouteImport } from './routes/_authenticated/admin.logs.integracoes'
import { Route as AuthenticatedAdminLogsGatilhosRouteImport } from './routes/_authenticated/admin.logs.gatilhos'
import { Route as AuthenticatedAdminIntegracoesSlugRouteImport } from './routes/_authenticated/admin.integracoes_.$slug'
import { Route as ApiPublicHooksPixItauSplatRouteImport } from './routes/api/public/hooks/pix-itau.$'

const TvGeralRoute = TvGeralRouteImport.update({
  id: '/tv-geral',
  path: '/tv-geral',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMarketingIndexRoute =
  AuthenticatedMarketingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedCarregadoresIndexRoute =
  AuthenticatedCarregadoresIndexRouteImport.update({
    id: '/carregadores/',
    path: '/carregadores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicAppVersionRoute = ApiPublicAppVersionRouteImport.update({
  id: '/api/public/app-version',
  path: '/api/public/app-version',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSolarTarefasRoute =
  AuthenticatedSolarTarefasRouteImport.update({
    id: '/solar/tarefas',
    path: '/solar/tarefas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolarPedidosRoute =
  AuthenticatedSolarPedidosRouteImport.update({
    id: '/solar/pedidos',
    path: '/solar/pedidos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolarDashboardsRoute =
  AuthenticatedSolarDashboardsRouteImport.update({
    id: '/solar/dashboards',
    path: '/solar/dashboards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolarCuponsRoute =
  AuthenticatedSolarCuponsRouteImport.update({
    id: '/solar/cupons',
    path: '/solar/cupons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolarClientesRoute =
  AuthenticatedSolarClientesRouteImport.update({
    id: '/solar/clientes',
    path: '/solar/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolarAtlasRoute = AuthenticatedSolarAtlasRouteImport.update({
  id: '/solar/atlas',
  path: '/solar/atlas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingTrafegoRoute =
  AuthenticatedMarketingTrafegoRouteImport.update({
    id: '/trafego',
    path: '/trafego',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingSocialRoute =
  AuthenticatedMarketingSocialRouteImport.update({
    id: '/social',
    path: '/social',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingPreVendasRoute =
  AuthenticatedMarketingPreVendasRouteImport.update({
    id: '/pre-vendas',
    path: '/pre-vendas',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingMetasRoute =
  AuthenticatedMarketingMetasRouteImport.update({
    id: '/metas',
    path: '/metas',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingGargaloRoute =
  AuthenticatedMarketingGargaloRouteImport.update({
    id: '/gargalo',
    path: '/gargalo',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingCohortRoute =
  AuthenticatedMarketingCohortRouteImport.update({
    id: '/cohort',
    path: '/cohort',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingCacRoute =
  AuthenticatedMarketingCacRouteImport.update({
    id: '/cac',
    path: '/cac',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedCarregadoresTarefasRoute =
  AuthenticatedCarregadoresTarefasRouteImport.update({
    id: '/carregadores/tarefas',
    path: '/carregadores/tarefas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarregadoresRegrasRoute =
  AuthenticatedCarregadoresRegrasRouteImport.update({
    id: '/carregadores/regras',
    path: '/carregadores/regras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarregadoresPropostasRoute =
  AuthenticatedCarregadoresPropostasRouteImport.update({
    id: '/carregadores/propostas',
    path: '/carregadores/propostas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarregadoresProdutosRoute =
  AuthenticatedCarregadoresProdutosRouteImport.update({
    id: '/carregadores/produtos',
    path: '/carregadores/produtos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarregadoresPedidosRoute =
  AuthenticatedCarregadoresPedidosRouteImport.update({
    id: '/carregadores/pedidos',
    path: '/carregadores/pedidos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarregadoresMetasRoute =
  AuthenticatedCarregadoresMetasRouteImport.update({
    id: '/carregadores/metas',
    path: '/carregadores/metas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarregadoresFreteRegrasRoute =
  AuthenticatedCarregadoresFreteRegrasRouteImport.update({
    id: '/carregadores/frete-regras',
    path: '/carregadores/frete-regras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarregadoresComissoesRoute =
  AuthenticatedCarregadoresComissoesRouteImport.update({
    id: '/carregadores/comissoes',
    path: '/carregadores/comissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarregadoresClientesRoute =
  AuthenticatedCarregadoresClientesRouteImport.update({
    id: '/carregadores/clientes',
    path: '/carregadores/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVinculosRoute =
  AuthenticatedAdminVinculosRouteImport.update({
    id: '/admin/vinculos',
    path: '/admin/vinculos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTabelasRoute =
  AuthenticatedAdminTabelasRouteImport.update({
    id: '/admin/tabelas',
    path: '/admin/tabelas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRegrasRoute =
  AuthenticatedAdminRegrasRouteImport.update({
    id: '/admin/regras',
    path: '/admin/regras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProdutosSolarRoute =
  AuthenticatedAdminProdutosSolarRouteImport.update({
    id: '/admin/produtos-solar',
    path: '/admin/produtos-solar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/admin/produtos',
    path: '/admin/produtos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPerfisRoute =
  AuthenticatedAdminPerfisRouteImport.update({
    id: '/admin/perfis',
    path: '/admin/perfis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminModulosSolarRoute =
  AuthenticatedAdminModulosSolarRouteImport.update({
    id: '/admin/modulos-solar',
    path: '/admin/modulos-solar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminModeracaoRoute =
  AuthenticatedAdminModeracaoRouteImport.update({
    id: '/admin/moderacao',
    path: '/admin/moderacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMetasRoute = AuthenticatedAdminMetasRouteImport.update({
  id: '/admin/metas',
  path: '/admin/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIntegracoesRoute =
  AuthenticatedAdminIntegracoesRouteImport.update({
    id: '/admin/integracoes',
    path: '/admin/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFreteRegrasRoute =
  AuthenticatedAdminFreteRegrasRouteImport.update({
    id: '/admin/frete-regras',
    path: '/admin/frete-regras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEstoqueRoute =
  AuthenticatedAdminEstoqueRouteImport.update({
    id: '/admin/estoque',
    path: '/admin/estoque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/admin/configuracoes',
    path: '/admin/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminComissoesRoute =
  AuthenticatedAdminComissoesRouteImport.update({
    id: '/admin/comissoes',
    path: '/admin/comissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/admin/auditoria',
    path: '/admin/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAtividadeRoute =
  AuthenticatedAdminAtividadeRouteImport.update({
    id: '/admin/atividade',
    path: '/admin/atividade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSolarPropostasIndexRoute =
  AuthenticatedSolarPropostasIndexRouteImport.update({
    id: '/solar/propostas/',
    path: '/solar/propostas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarregadoresPropostasIndexRoute =
  AuthenticatedCarregadoresPropostasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCarregadoresPropostasRoute,
  } as any)
const AuthenticatedCarregadoresClientesIndexRoute =
  AuthenticatedCarregadoresClientesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCarregadoresClientesRoute,
  } as any)
const AuthenticatedAdminLogsIndexRoute =
  AuthenticatedAdminLogsIndexRouteImport.update({
    id: '/admin/logs/',
    path: '/admin/logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSapNfsRoute = ApiPublicHooksSapNfsRouteImport.update({
  id: '/api/public/hooks/sap-nfs',
  path: '/api/public/hooks/sap-nfs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPixItauRoute = ApiPublicHooksPixItauRouteImport.update({
  id: '/api/public/hooks/pix-itau',
  path: '/api/public/hooks/pix-itau',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPagamentoLinkRoute =
  ApiPublicHooksPagamentoLinkRouteImport.update({
    id: '/api/public/hooks/pagamento-link',
    path: '/api/public/hooks/pagamento-link',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFretefyTrackingRoute =
  ApiPublicHooksFretefyTrackingRouteImport.update({
    id: '/api/public/hooks/fretefy-tracking',
    path: '/api/public/hooks/fretefy-tracking',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSolarPropostasNovaRoute =
  AuthenticatedSolarPropostasNovaRouteImport.update({
    id: '/solar/propostas/nova',
    path: '/solar/propostas/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolarDashboardsMetasRoute =
  AuthenticatedSolarDashboardsMetasRouteImport.update({
    id: '/metas',
    path: '/metas',
    getParentRoute: () => AuthenticatedSolarDashboardsRoute,
  } as any)
const AuthenticatedSolarClientesSugestoesRoute =
  AuthenticatedSolarClientesSugestoesRouteImport.update({
    id: '/sugestoes',
    path: '/sugestoes',
    getParentRoute: () => AuthenticatedSolarClientesRoute,
  } as any)
const AuthenticatedSolarClientesSegmentacaoRoute =
  AuthenticatedSolarClientesSegmentacaoRouteImport.update({
    id: '/segmentacao',
    path: '/segmentacao',
    getParentRoute: () => AuthenticatedSolarClientesRoute,
  } as any)
const AuthenticatedSolarClientesRankingRoute =
  AuthenticatedSolarClientesRankingRouteImport.update({
    id: '/ranking',
    path: '/ranking',
    getParentRoute: () => AuthenticatedSolarClientesRoute,
  } as any)
const AuthenticatedSolarClientesPerfilRoute =
  AuthenticatedSolarClientesPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedSolarClientesRoute,
  } as any)
const AuthenticatedSolarClientesCadastrosRoute =
  AuthenticatedSolarClientesCadastrosRouteImport.update({
    id: '/cadastros',
    path: '/cadastros',
    getParentRoute: () => AuthenticatedSolarClientesRoute,
  } as any)
const AuthenticatedCarregadoresPropostasVisualizarRoute =
  AuthenticatedCarregadoresPropostasVisualizarRouteImport.update({
    id: '/visualizar',
    path: '/visualizar',
    getParentRoute: () => AuthenticatedCarregadoresPropostasRoute,
  } as any)
const AuthenticatedCarregadoresPropostasNovaRoute =
  AuthenticatedCarregadoresPropostasNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedCarregadoresPropostasRoute,
  } as any)
const AuthenticatedCarregadoresPropostasAuditoriaRoute =
  AuthenticatedCarregadoresPropostasAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedCarregadoresPropostasRoute,
  } as any)
const AuthenticatedCarregadoresClientesCadastrosRoute =
  AuthenticatedCarregadoresClientesCadastrosRouteImport.update({
    id: '/cadastros',
    path: '/cadastros',
    getParentRoute: () => AuthenticatedCarregadoresClientesRoute,
  } as any)
const AuthenticatedAdminLogsRetencaoRoute =
  AuthenticatedAdminLogsRetencaoRouteImport.update({
    id: '/admin/logs/retencao',
    path: '/admin/logs/retencao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLogsModeracaoRoute =
  AuthenticatedAdminLogsModeracaoRouteImport.update({
    id: '/admin/logs/moderacao',
    path: '/admin/logs/moderacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLogsIntegracoesRoute =
  AuthenticatedAdminLogsIntegracoesRouteImport.update({
    id: '/admin/logs/integracoes',
    path: '/admin/logs/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLogsGatilhosRoute =
  AuthenticatedAdminLogsGatilhosRouteImport.update({
    id: '/admin/logs/gatilhos',
    path: '/admin/logs/gatilhos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIntegracoesSlugRoute =
  AuthenticatedAdminIntegracoesSlugRouteImport.update({
    id: '/admin/integracoes_/$slug',
    path: '/admin/integracoes/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksPixItauSplatRoute =
  ApiPublicHooksPixItauSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => ApiPublicHooksPixItauRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tv-geral': typeof TvGeralRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/marketing': typeof AuthenticatedMarketingRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/atividade': typeof AuthenticatedAdminAtividadeRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/comissoes': typeof AuthenticatedAdminComissoesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/frete-regras': typeof AuthenticatedAdminFreteRegrasRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/admin/metas': typeof AuthenticatedAdminMetasRoute
  '/admin/moderacao': typeof AuthenticatedAdminModeracaoRoute
  '/admin/modulos-solar': typeof AuthenticatedAdminModulosSolarRoute
  '/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/produtos-solar': typeof AuthenticatedAdminProdutosSolarRoute
  '/admin/regras': typeof AuthenticatedAdminRegrasRoute
  '/admin/tabelas': typeof AuthenticatedAdminTabelasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/vinculos': typeof AuthenticatedAdminVinculosRoute
  '/carregadores/clientes': typeof AuthenticatedCarregadoresClientesRouteWithChildren
  '/carregadores/comissoes': typeof AuthenticatedCarregadoresComissoesRoute
  '/carregadores/frete-regras': typeof AuthenticatedCarregadoresFreteRegrasRoute
  '/carregadores/metas': typeof AuthenticatedCarregadoresMetasRoute
  '/carregadores/pedidos': typeof AuthenticatedCarregadoresPedidosRoute
  '/carregadores/produtos': typeof AuthenticatedCarregadoresProdutosRoute
  '/carregadores/propostas': typeof AuthenticatedCarregadoresPropostasRouteWithChildren
  '/carregadores/regras': typeof AuthenticatedCarregadoresRegrasRoute
  '/carregadores/tarefas': typeof AuthenticatedCarregadoresTarefasRoute
  '/marketing/cac': typeof AuthenticatedMarketingCacRoute
  '/marketing/cohort': typeof AuthenticatedMarketingCohortRoute
  '/marketing/gargalo': typeof AuthenticatedMarketingGargaloRoute
  '/marketing/metas': typeof AuthenticatedMarketingMetasRoute
  '/marketing/pre-vendas': typeof AuthenticatedMarketingPreVendasRoute
  '/marketing/social': typeof AuthenticatedMarketingSocialRoute
  '/marketing/trafego': typeof AuthenticatedMarketingTrafegoRoute
  '/solar/atlas': typeof AuthenticatedSolarAtlasRoute
  '/solar/clientes': typeof AuthenticatedSolarClientesRouteWithChildren
  '/solar/cupons': typeof AuthenticatedSolarCuponsRoute
  '/solar/dashboards': typeof AuthenticatedSolarDashboardsRouteWithChildren
  '/solar/pedidos': typeof AuthenticatedSolarPedidosRoute
  '/solar/tarefas': typeof AuthenticatedSolarTarefasRoute
  '/api/public/app-version': typeof ApiPublicAppVersionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/carregadores/': typeof AuthenticatedCarregadoresIndexRoute
  '/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/admin/integracoes/$slug': typeof AuthenticatedAdminIntegracoesSlugRoute
  '/admin/logs/gatilhos': typeof AuthenticatedAdminLogsGatilhosRoute
  '/admin/logs/integracoes': typeof AuthenticatedAdminLogsIntegracoesRoute
  '/admin/logs/moderacao': typeof AuthenticatedAdminLogsModeracaoRoute
  '/admin/logs/retencao': typeof AuthenticatedAdminLogsRetencaoRoute
  '/carregadores/clientes/cadastros': typeof AuthenticatedCarregadoresClientesCadastrosRoute
  '/carregadores/propostas/auditoria': typeof AuthenticatedCarregadoresPropostasAuditoriaRoute
  '/carregadores/propostas/nova': typeof AuthenticatedCarregadoresPropostasNovaRoute
  '/carregadores/propostas/visualizar': typeof AuthenticatedCarregadoresPropostasVisualizarRoute
  '/solar/clientes/cadastros': typeof AuthenticatedSolarClientesCadastrosRoute
  '/solar/clientes/perfil': typeof AuthenticatedSolarClientesPerfilRoute
  '/solar/clientes/ranking': typeof AuthenticatedSolarClientesRankingRoute
  '/solar/clientes/segmentacao': typeof AuthenticatedSolarClientesSegmentacaoRoute
  '/solar/clientes/sugestoes': typeof AuthenticatedSolarClientesSugestoesRoute
  '/solar/dashboards/metas': typeof AuthenticatedSolarDashboardsMetasRoute
  '/solar/propostas/nova': typeof AuthenticatedSolarPropostasNovaRoute
  '/api/public/hooks/fretefy-tracking': typeof ApiPublicHooksFretefyTrackingRoute
  '/api/public/hooks/pagamento-link': typeof ApiPublicHooksPagamentoLinkRoute
  '/api/public/hooks/pix-itau': typeof ApiPublicHooksPixItauRouteWithChildren
  '/api/public/hooks/sap-nfs': typeof ApiPublicHooksSapNfsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/logs/': typeof AuthenticatedAdminLogsIndexRoute
  '/carregadores/clientes/': typeof AuthenticatedCarregadoresClientesIndexRoute
  '/carregadores/propostas/': typeof AuthenticatedCarregadoresPropostasIndexRoute
  '/solar/propostas/': typeof AuthenticatedSolarPropostasIndexRoute
  '/api/public/hooks/pix-itau/$': typeof ApiPublicHooksPixItauSplatRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tv-geral': typeof TvGeralRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/atividade': typeof AuthenticatedAdminAtividadeRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/comissoes': typeof AuthenticatedAdminComissoesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/frete-regras': typeof AuthenticatedAdminFreteRegrasRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/admin/metas': typeof AuthenticatedAdminMetasRoute
  '/admin/moderacao': typeof AuthenticatedAdminModeracaoRoute
  '/admin/modulos-solar': typeof AuthenticatedAdminModulosSolarRoute
  '/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/produtos-solar': typeof AuthenticatedAdminProdutosSolarRoute
  '/admin/regras': typeof AuthenticatedAdminRegrasRoute
  '/admin/tabelas': typeof AuthenticatedAdminTabelasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/vinculos': typeof AuthenticatedAdminVinculosRoute
  '/carregadores/comissoes': typeof AuthenticatedCarregadoresComissoesRoute
  '/carregadores/frete-regras': typeof AuthenticatedCarregadoresFreteRegrasRoute
  '/carregadores/metas': typeof AuthenticatedCarregadoresMetasRoute
  '/carregadores/pedidos': typeof AuthenticatedCarregadoresPedidosRoute
  '/carregadores/produtos': typeof AuthenticatedCarregadoresProdutosRoute
  '/carregadores/regras': typeof AuthenticatedCarregadoresRegrasRoute
  '/carregadores/tarefas': typeof AuthenticatedCarregadoresTarefasRoute
  '/marketing/cac': typeof AuthenticatedMarketingCacRoute
  '/marketing/cohort': typeof AuthenticatedMarketingCohortRoute
  '/marketing/gargalo': typeof AuthenticatedMarketingGargaloRoute
  '/marketing/metas': typeof AuthenticatedMarketingMetasRoute
  '/marketing/pre-vendas': typeof AuthenticatedMarketingPreVendasRoute
  '/marketing/social': typeof AuthenticatedMarketingSocialRoute
  '/marketing/trafego': typeof AuthenticatedMarketingTrafegoRoute
  '/solar/atlas': typeof AuthenticatedSolarAtlasRoute
  '/solar/clientes': typeof AuthenticatedSolarClientesRouteWithChildren
  '/solar/cupons': typeof AuthenticatedSolarCuponsRoute
  '/solar/dashboards': typeof AuthenticatedSolarDashboardsRouteWithChildren
  '/solar/pedidos': typeof AuthenticatedSolarPedidosRoute
  '/solar/tarefas': typeof AuthenticatedSolarTarefasRoute
  '/api/public/app-version': typeof ApiPublicAppVersionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/carregadores': typeof AuthenticatedCarregadoresIndexRoute
  '/marketing': typeof AuthenticatedMarketingIndexRoute
  '/admin/integracoes/$slug': typeof AuthenticatedAdminIntegracoesSlugRoute
  '/admin/logs/gatilhos': typeof AuthenticatedAdminLogsGatilhosRoute
  '/admin/logs/integracoes': typeof AuthenticatedAdminLogsIntegracoesRoute
  '/admin/logs/moderacao': typeof AuthenticatedAdminLogsModeracaoRoute
  '/admin/logs/retencao': typeof AuthenticatedAdminLogsRetencaoRoute
  '/carregadores/clientes/cadastros': typeof AuthenticatedCarregadoresClientesCadastrosRoute
  '/carregadores/propostas/auditoria': typeof AuthenticatedCarregadoresPropostasAuditoriaRoute
  '/carregadores/propostas/nova': typeof AuthenticatedCarregadoresPropostasNovaRoute
  '/carregadores/propostas/visualizar': typeof AuthenticatedCarregadoresPropostasVisualizarRoute
  '/solar/clientes/cadastros': typeof AuthenticatedSolarClientesCadastrosRoute
  '/solar/clientes/perfil': typeof AuthenticatedSolarClientesPerfilRoute
  '/solar/clientes/ranking': typeof AuthenticatedSolarClientesRankingRoute
  '/solar/clientes/segmentacao': typeof AuthenticatedSolarClientesSegmentacaoRoute
  '/solar/clientes/sugestoes': typeof AuthenticatedSolarClientesSugestoesRoute
  '/solar/dashboards/metas': typeof AuthenticatedSolarDashboardsMetasRoute
  '/solar/propostas/nova': typeof AuthenticatedSolarPropostasNovaRoute
  '/api/public/hooks/fretefy-tracking': typeof ApiPublicHooksFretefyTrackingRoute
  '/api/public/hooks/pagamento-link': typeof ApiPublicHooksPagamentoLinkRoute
  '/api/public/hooks/pix-itau': typeof ApiPublicHooksPixItauRouteWithChildren
  '/api/public/hooks/sap-nfs': typeof ApiPublicHooksSapNfsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/logs': typeof AuthenticatedAdminLogsIndexRoute
  '/carregadores/clientes': typeof AuthenticatedCarregadoresClientesIndexRoute
  '/carregadores/propostas': typeof AuthenticatedCarregadoresPropostasIndexRoute
  '/solar/propostas': typeof AuthenticatedSolarPropostasIndexRoute
  '/api/public/hooks/pix-itau/$': typeof ApiPublicHooksPixItauSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tv-geral': typeof TvGeralRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/atividade': typeof AuthenticatedAdminAtividadeRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/comissoes': typeof AuthenticatedAdminComissoesRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/_authenticated/admin/frete-regras': typeof AuthenticatedAdminFreteRegrasRoute
  '/_authenticated/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/_authenticated/admin/metas': typeof AuthenticatedAdminMetasRoute
  '/_authenticated/admin/moderacao': typeof AuthenticatedAdminModeracaoRoute
  '/_authenticated/admin/modulos-solar': typeof AuthenticatedAdminModulosSolarRoute
  '/_authenticated/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/_authenticated/admin/produtos-solar': typeof AuthenticatedAdminProdutosSolarRoute
  '/_authenticated/admin/regras': typeof AuthenticatedAdminRegrasRoute
  '/_authenticated/admin/tabelas': typeof AuthenticatedAdminTabelasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/vinculos': typeof AuthenticatedAdminVinculosRoute
  '/_authenticated/carregadores/clientes': typeof AuthenticatedCarregadoresClientesRouteWithChildren
  '/_authenticated/carregadores/comissoes': typeof AuthenticatedCarregadoresComissoesRoute
  '/_authenticated/carregadores/frete-regras': typeof AuthenticatedCarregadoresFreteRegrasRoute
  '/_authenticated/carregadores/metas': typeof AuthenticatedCarregadoresMetasRoute
  '/_authenticated/carregadores/pedidos': typeof AuthenticatedCarregadoresPedidosRoute
  '/_authenticated/carregadores/produtos': typeof AuthenticatedCarregadoresProdutosRoute
  '/_authenticated/carregadores/propostas': typeof AuthenticatedCarregadoresPropostasRouteWithChildren
  '/_authenticated/carregadores/regras': typeof AuthenticatedCarregadoresRegrasRoute
  '/_authenticated/carregadores/tarefas': typeof AuthenticatedCarregadoresTarefasRoute
  '/_authenticated/marketing/cac': typeof AuthenticatedMarketingCacRoute
  '/_authenticated/marketing/cohort': typeof AuthenticatedMarketingCohortRoute
  '/_authenticated/marketing/gargalo': typeof AuthenticatedMarketingGargaloRoute
  '/_authenticated/marketing/metas': typeof AuthenticatedMarketingMetasRoute
  '/_authenticated/marketing/pre-vendas': typeof AuthenticatedMarketingPreVendasRoute
  '/_authenticated/marketing/social': typeof AuthenticatedMarketingSocialRoute
  '/_authenticated/marketing/trafego': typeof AuthenticatedMarketingTrafegoRoute
  '/_authenticated/solar/atlas': typeof AuthenticatedSolarAtlasRoute
  '/_authenticated/solar/clientes': typeof AuthenticatedSolarClientesRouteWithChildren
  '/_authenticated/solar/cupons': typeof AuthenticatedSolarCuponsRoute
  '/_authenticated/solar/dashboards': typeof AuthenticatedSolarDashboardsRouteWithChildren
  '/_authenticated/solar/pedidos': typeof AuthenticatedSolarPedidosRoute
  '/_authenticated/solar/tarefas': typeof AuthenticatedSolarTarefasRoute
  '/api/public/app-version': typeof ApiPublicAppVersionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/carregadores/': typeof AuthenticatedCarregadoresIndexRoute
  '/_authenticated/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/_authenticated/admin/integracoes_/$slug': typeof AuthenticatedAdminIntegracoesSlugRoute
  '/_authenticated/admin/logs/gatilhos': typeof AuthenticatedAdminLogsGatilhosRoute
  '/_authenticated/admin/logs/integracoes': typeof AuthenticatedAdminLogsIntegracoesRoute
  '/_authenticated/admin/logs/moderacao': typeof AuthenticatedAdminLogsModeracaoRoute
  '/_authenticated/admin/logs/retencao': typeof AuthenticatedAdminLogsRetencaoRoute
  '/_authenticated/carregadores/clientes/cadastros': typeof AuthenticatedCarregadoresClientesCadastrosRoute
  '/_authenticated/carregadores/propostas/auditoria': typeof AuthenticatedCarregadoresPropostasAuditoriaRoute
  '/_authenticated/carregadores/propostas/nova': typeof AuthenticatedCarregadoresPropostasNovaRoute
  '/_authenticated/carregadores/propostas/visualizar': typeof AuthenticatedCarregadoresPropostasVisualizarRoute
  '/_authenticated/solar/clientes/cadastros': typeof AuthenticatedSolarClientesCadastrosRoute
  '/_authenticated/solar/clientes/perfil': typeof AuthenticatedSolarClientesPerfilRoute
  '/_authenticated/solar/clientes/ranking': typeof AuthenticatedSolarClientesRankingRoute
  '/_authenticated/solar/clientes/segmentacao': typeof AuthenticatedSolarClientesSegmentacaoRoute
  '/_authenticated/solar/clientes/sugestoes': typeof AuthenticatedSolarClientesSugestoesRoute
  '/_authenticated/solar/dashboards/metas': typeof AuthenticatedSolarDashboardsMetasRoute
  '/_authenticated/solar/propostas/nova': typeof AuthenticatedSolarPropostasNovaRoute
  '/api/public/hooks/fretefy-tracking': typeof ApiPublicHooksFretefyTrackingRoute
  '/api/public/hooks/pagamento-link': typeof ApiPublicHooksPagamentoLinkRoute
  '/api/public/hooks/pix-itau': typeof ApiPublicHooksPixItauRouteWithChildren
  '/api/public/hooks/sap-nfs': typeof ApiPublicHooksSapNfsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/admin/logs/': typeof AuthenticatedAdminLogsIndexRoute
  '/_authenticated/carregadores/clientes/': typeof AuthenticatedCarregadoresClientesIndexRoute
  '/_authenticated/carregadores/propostas/': typeof AuthenticatedCarregadoresPropostasIndexRoute
  '/_authenticated/solar/propostas/': typeof AuthenticatedSolarPropostasIndexRoute
  '/api/public/hooks/pix-itau/$': typeof ApiPublicHooksPixItauSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tv-geral'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/marketing'
    | '/perfil'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/atividade'
    | '/admin/auditoria'
    | '/admin/comissoes'
    | '/admin/configuracoes'
    | '/admin/estoque'
    | '/admin/frete-regras'
    | '/admin/integracoes'
    | '/admin/metas'
    | '/admin/moderacao'
    | '/admin/modulos-solar'
    | '/admin/perfis'
    | '/admin/produtos'
    | '/admin/produtos-solar'
    | '/admin/regras'
    | '/admin/tabelas'
    | '/admin/usuarios'
    | '/admin/vinculos'
    | '/carregadores/clientes'
    | '/carregadores/comissoes'
    | '/carregadores/frete-regras'
    | '/carregadores/metas'
    | '/carregadores/pedidos'
    | '/carregadores/produtos'
    | '/carregadores/propostas'
    | '/carregadores/regras'
    | '/carregadores/tarefas'
    | '/marketing/cac'
    | '/marketing/cohort'
    | '/marketing/gargalo'
    | '/marketing/metas'
    | '/marketing/pre-vendas'
    | '/marketing/social'
    | '/marketing/trafego'
    | '/solar/atlas'
    | '/solar/clientes'
    | '/solar/cupons'
    | '/solar/dashboards'
    | '/solar/pedidos'
    | '/solar/tarefas'
    | '/api/public/app-version'
    | '/admin/'
    | '/carregadores/'
    | '/marketing/'
    | '/admin/integracoes/$slug'
    | '/admin/logs/gatilhos'
    | '/admin/logs/integracoes'
    | '/admin/logs/moderacao'
    | '/admin/logs/retencao'
    | '/carregadores/clientes/cadastros'
    | '/carregadores/propostas/auditoria'
    | '/carregadores/propostas/nova'
    | '/carregadores/propostas/visualizar'
    | '/solar/clientes/cadastros'
    | '/solar/clientes/perfil'
    | '/solar/clientes/ranking'
    | '/solar/clientes/segmentacao'
    | '/solar/clientes/sugestoes'
    | '/solar/dashboards/metas'
    | '/solar/propostas/nova'
    | '/api/public/hooks/fretefy-tracking'
    | '/api/public/hooks/pagamento-link'
    | '/api/public/hooks/pix-itau'
    | '/api/public/hooks/sap-nfs'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/logs/'
    | '/carregadores/clientes/'
    | '/carregadores/propostas/'
    | '/solar/propostas/'
    | '/api/public/hooks/pix-itau/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tv-geral'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/perfil'
    | '/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/atividade'
    | '/admin/auditoria'
    | '/admin/comissoes'
    | '/admin/configuracoes'
    | '/admin/estoque'
    | '/admin/frete-regras'
    | '/admin/integracoes'
    | '/admin/metas'
    | '/admin/moderacao'
    | '/admin/modulos-solar'
    | '/admin/perfis'
    | '/admin/produtos'
    | '/admin/produtos-solar'
    | '/admin/regras'
    | '/admin/tabelas'
    | '/admin/usuarios'
    | '/admin/vinculos'
    | '/carregadores/comissoes'
    | '/carregadores/frete-regras'
    | '/carregadores/metas'
    | '/carregadores/pedidos'
    | '/carregadores/produtos'
    | '/carregadores/regras'
    | '/carregadores/tarefas'
    | '/marketing/cac'
    | '/marketing/cohort'
    | '/marketing/gargalo'
    | '/marketing/metas'
    | '/marketing/pre-vendas'
    | '/marketing/social'
    | '/marketing/trafego'
    | '/solar/atlas'
    | '/solar/clientes'
    | '/solar/cupons'
    | '/solar/dashboards'
    | '/solar/pedidos'
    | '/solar/tarefas'
    | '/api/public/app-version'
    | '/admin'
    | '/carregadores'
    | '/marketing'
    | '/admin/integracoes/$slug'
    | '/admin/logs/gatilhos'
    | '/admin/logs/integracoes'
    | '/admin/logs/moderacao'
    | '/admin/logs/retencao'
    | '/carregadores/clientes/cadastros'
    | '/carregadores/propostas/auditoria'
    | '/carregadores/propostas/nova'
    | '/carregadores/propostas/visualizar'
    | '/solar/clientes/cadastros'
    | '/solar/clientes/perfil'
    | '/solar/clientes/ranking'
    | '/solar/clientes/segmentacao'
    | '/solar/clientes/sugestoes'
    | '/solar/dashboards/metas'
    | '/solar/propostas/nova'
    | '/api/public/hooks/fretefy-tracking'
    | '/api/public/hooks/pagamento-link'
    | '/api/public/hooks/pix-itau'
    | '/api/public/hooks/sap-nfs'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/logs'
    | '/carregadores/clientes'
    | '/carregadores/propostas'
    | '/solar/propostas'
    | '/api/public/hooks/pix-itau/$'
  id:
    | '__root__'
    | '/_authenticated'
    | '/$'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tv-geral'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/marketing'
    | '/_authenticated/perfil'
    | '/_authenticated/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/atividade'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/comissoes'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/estoque'
    | '/_authenticated/admin/frete-regras'
    | '/_authenticated/admin/integracoes'
    | '/_authenticated/admin/metas'
    | '/_authenticated/admin/moderacao'
    | '/_authenticated/admin/modulos-solar'
    | '/_authenticated/admin/perfis'
    | '/_authenticated/admin/produtos'
    | '/_authenticated/admin/produtos-solar'
    | '/_authenticated/admin/regras'
    | '/_authenticated/admin/tabelas'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/vinculos'
    | '/_authenticated/carregadores/clientes'
    | '/_authenticated/carregadores/comissoes'
    | '/_authenticated/carregadores/frete-regras'
    | '/_authenticated/carregadores/metas'
    | '/_authenticated/carregadores/pedidos'
    | '/_authenticated/carregadores/produtos'
    | '/_authenticated/carregadores/propostas'
    | '/_authenticated/carregadores/regras'
    | '/_authenticated/carregadores/tarefas'
    | '/_authenticated/marketing/cac'
    | '/_authenticated/marketing/cohort'
    | '/_authenticated/marketing/gargalo'
    | '/_authenticated/marketing/metas'
    | '/_authenticated/marketing/pre-vendas'
    | '/_authenticated/marketing/social'
    | '/_authenticated/marketing/trafego'
    | '/_authenticated/solar/atlas'
    | '/_authenticated/solar/clientes'
    | '/_authenticated/solar/cupons'
    | '/_authenticated/solar/dashboards'
    | '/_authenticated/solar/pedidos'
    | '/_authenticated/solar/tarefas'
    | '/api/public/app-version'
    | '/_authenticated/admin/'
    | '/_authenticated/carregadores/'
    | '/_authenticated/marketing/'
    | '/_authenticated/admin/integracoes_/$slug'
    | '/_authenticated/admin/logs/gatilhos'
    | '/_authenticated/admin/logs/integracoes'
    | '/_authenticated/admin/logs/moderacao'
    | '/_authenticated/admin/logs/retencao'
    | '/_authenticated/carregadores/clientes/cadastros'
    | '/_authenticated/carregadores/propostas/auditoria'
    | '/_authenticated/carregadores/propostas/nova'
    | '/_authenticated/carregadores/propostas/visualizar'
    | '/_authenticated/solar/clientes/cadastros'
    | '/_authenticated/solar/clientes/perfil'
    | '/_authenticated/solar/clientes/ranking'
    | '/_authenticated/solar/clientes/segmentacao'
    | '/_authenticated/solar/clientes/sugestoes'
    | '/_authenticated/solar/dashboards/metas'
    | '/_authenticated/solar/propostas/nova'
    | '/api/public/hooks/fretefy-tracking'
    | '/api/public/hooks/pagamento-link'
    | '/api/public/hooks/pix-itau'
    | '/api/public/hooks/sap-nfs'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/admin/logs/'
    | '/_authenticated/carregadores/clientes/'
    | '/_authenticated/carregadores/propostas/'
    | '/_authenticated/solar/propostas/'
    | '/api/public/hooks/pix-itau/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TvGeralRoute: typeof TvGeralRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicAppVersionRoute: typeof ApiPublicAppVersionRoute
  ApiPublicHooksFretefyTrackingRoute: typeof ApiPublicHooksFretefyTrackingRoute
  ApiPublicHooksPagamentoLinkRoute: typeof ApiPublicHooksPagamentoLinkRoute
  ApiPublicHooksPixItauRoute: typeof ApiPublicHooksPixItauRouteWithChildren
  ApiPublicHooksSapNfsRoute: typeof ApiPublicHooksSapNfsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv-geral': {
      id: '/tv-geral'
      path: '/tv-geral'
      fullPath: '/tv-geral'
      preLoaderRoute: typeof TvGeralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/marketing/': {
      id: '/_authenticated/marketing/'
      path: '/'
      fullPath: '/marketing/'
      preLoaderRoute: typeof AuthenticatedMarketingIndexRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/carregadores/': {
      id: '/_authenticated/carregadores/'
      path: '/carregadores'
      fullPath: '/carregadores/'
      preLoaderRoute: typeof AuthenticatedCarregadoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/app-version': {
      id: '/api/public/app-version'
      path: '/api/public/app-version'
      fullPath: '/api/public/app-version'
      preLoaderRoute: typeof ApiPublicAppVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/solar/tarefas': {
      id: '/_authenticated/solar/tarefas'
      path: '/solar/tarefas'
      fullPath: '/solar/tarefas'
      preLoaderRoute: typeof AuthenticatedSolarTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solar/pedidos': {
      id: '/_authenticated/solar/pedidos'
      path: '/solar/pedidos'
      fullPath: '/solar/pedidos'
      preLoaderRoute: typeof AuthenticatedSolarPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solar/dashboards': {
      id: '/_authenticated/solar/dashboards'
      path: '/solar/dashboards'
      fullPath: '/solar/dashboards'
      preLoaderRoute: typeof AuthenticatedSolarDashboardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solar/cupons': {
      id: '/_authenticated/solar/cupons'
      path: '/solar/cupons'
      fullPath: '/solar/cupons'
      preLoaderRoute: typeof AuthenticatedSolarCuponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solar/clientes': {
      id: '/_authenticated/solar/clientes'
      path: '/solar/clientes'
      fullPath: '/solar/clientes'
      preLoaderRoute: typeof AuthenticatedSolarClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solar/atlas': {
      id: '/_authenticated/solar/atlas'
      path: '/solar/atlas'
      fullPath: '/solar/atlas'
      preLoaderRoute: typeof AuthenticatedSolarAtlasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing/trafego': {
      id: '/_authenticated/marketing/trafego'
      path: '/trafego'
      fullPath: '/marketing/trafego'
      preLoaderRoute: typeof AuthenticatedMarketingTrafegoRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/social': {
      id: '/_authenticated/marketing/social'
      path: '/social'
      fullPath: '/marketing/social'
      preLoaderRoute: typeof AuthenticatedMarketingSocialRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/pre-vendas': {
      id: '/_authenticated/marketing/pre-vendas'
      path: '/pre-vendas'
      fullPath: '/marketing/pre-vendas'
      preLoaderRoute: typeof AuthenticatedMarketingPreVendasRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/metas': {
      id: '/_authenticated/marketing/metas'
      path: '/metas'
      fullPath: '/marketing/metas'
      preLoaderRoute: typeof AuthenticatedMarketingMetasRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/gargalo': {
      id: '/_authenticated/marketing/gargalo'
      path: '/gargalo'
      fullPath: '/marketing/gargalo'
      preLoaderRoute: typeof AuthenticatedMarketingGargaloRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/cohort': {
      id: '/_authenticated/marketing/cohort'
      path: '/cohort'
      fullPath: '/marketing/cohort'
      preLoaderRoute: typeof AuthenticatedMarketingCohortRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/cac': {
      id: '/_authenticated/marketing/cac'
      path: '/cac'
      fullPath: '/marketing/cac'
      preLoaderRoute: typeof AuthenticatedMarketingCacRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/carregadores/tarefas': {
      id: '/_authenticated/carregadores/tarefas'
      path: '/carregadores/tarefas'
      fullPath: '/carregadores/tarefas'
      preLoaderRoute: typeof AuthenticatedCarregadoresTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carregadores/regras': {
      id: '/_authenticated/carregadores/regras'
      path: '/carregadores/regras'
      fullPath: '/carregadores/regras'
      preLoaderRoute: typeof AuthenticatedCarregadoresRegrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carregadores/propostas': {
      id: '/_authenticated/carregadores/propostas'
      path: '/carregadores/propostas'
      fullPath: '/carregadores/propostas'
      preLoaderRoute: typeof AuthenticatedCarregadoresPropostasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carregadores/produtos': {
      id: '/_authenticated/carregadores/produtos'
      path: '/carregadores/produtos'
      fullPath: '/carregadores/produtos'
      preLoaderRoute: typeof AuthenticatedCarregadoresProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carregadores/pedidos': {
      id: '/_authenticated/carregadores/pedidos'
      path: '/carregadores/pedidos'
      fullPath: '/carregadores/pedidos'
      preLoaderRoute: typeof AuthenticatedCarregadoresPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carregadores/metas': {
      id: '/_authenticated/carregadores/metas'
      path: '/carregadores/metas'
      fullPath: '/carregadores/metas'
      preLoaderRoute: typeof AuthenticatedCarregadoresMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carregadores/frete-regras': {
      id: '/_authenticated/carregadores/frete-regras'
      path: '/carregadores/frete-regras'
      fullPath: '/carregadores/frete-regras'
      preLoaderRoute: typeof AuthenticatedCarregadoresFreteRegrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carregadores/comissoes': {
      id: '/_authenticated/carregadores/comissoes'
      path: '/carregadores/comissoes'
      fullPath: '/carregadores/comissoes'
      preLoaderRoute: typeof AuthenticatedCarregadoresComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carregadores/clientes': {
      id: '/_authenticated/carregadores/clientes'
      path: '/carregadores/clientes'
      fullPath: '/carregadores/clientes'
      preLoaderRoute: typeof AuthenticatedCarregadoresClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/vinculos': {
      id: '/_authenticated/admin/vinculos'
      path: '/admin/vinculos'
      fullPath: '/admin/vinculos'
      preLoaderRoute: typeof AuthenticatedAdminVinculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tabelas': {
      id: '/_authenticated/admin/tabelas'
      path: '/admin/tabelas'
      fullPath: '/admin/tabelas'
      preLoaderRoute: typeof AuthenticatedAdminTabelasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/regras': {
      id: '/_authenticated/admin/regras'
      path: '/admin/regras'
      fullPath: '/admin/regras'
      preLoaderRoute: typeof AuthenticatedAdminRegrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/produtos-solar': {
      id: '/_authenticated/admin/produtos-solar'
      path: '/admin/produtos-solar'
      fullPath: '/admin/produtos-solar'
      preLoaderRoute: typeof AuthenticatedAdminProdutosSolarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/perfis': {
      id: '/_authenticated/admin/perfis'
      path: '/admin/perfis'
      fullPath: '/admin/perfis'
      preLoaderRoute: typeof AuthenticatedAdminPerfisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/modulos-solar': {
      id: '/_authenticated/admin/modulos-solar'
      path: '/admin/modulos-solar'
      fullPath: '/admin/modulos-solar'
      preLoaderRoute: typeof AuthenticatedAdminModulosSolarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/moderacao': {
      id: '/_authenticated/admin/moderacao'
      path: '/admin/moderacao'
      fullPath: '/admin/moderacao'
      preLoaderRoute: typeof AuthenticatedAdminModeracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/metas': {
      id: '/_authenticated/admin/metas'
      path: '/admin/metas'
      fullPath: '/admin/metas'
      preLoaderRoute: typeof AuthenticatedAdminMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/integracoes': {
      id: '/_authenticated/admin/integracoes'
      path: '/admin/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AuthenticatedAdminIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/frete-regras': {
      id: '/_authenticated/admin/frete-regras'
      path: '/admin/frete-regras'
      fullPath: '/admin/frete-regras'
      preLoaderRoute: typeof AuthenticatedAdminFreteRegrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/estoque': {
      id: '/_authenticated/admin/estoque'
      path: '/admin/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AuthenticatedAdminEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/comissoes': {
      id: '/_authenticated/admin/comissoes'
      path: '/admin/comissoes'
      fullPath: '/admin/comissoes'
      preLoaderRoute: typeof AuthenticatedAdminComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/atividade': {
      id: '/_authenticated/admin/atividade'
      path: '/admin/atividade'
      fullPath: '/admin/atividade'
      preLoaderRoute: typeof AuthenticatedAdminAtividadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/solar/propostas/': {
      id: '/_authenticated/solar/propostas/'
      path: '/solar/propostas'
      fullPath: '/solar/propostas/'
      preLoaderRoute: typeof AuthenticatedSolarPropostasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carregadores/propostas/': {
      id: '/_authenticated/carregadores/propostas/'
      path: '/'
      fullPath: '/carregadores/propostas/'
      preLoaderRoute: typeof AuthenticatedCarregadoresPropostasIndexRouteImport
      parentRoute: typeof AuthenticatedCarregadoresPropostasRoute
    }
    '/_authenticated/carregadores/clientes/': {
      id: '/_authenticated/carregadores/clientes/'
      path: '/'
      fullPath: '/carregadores/clientes/'
      preLoaderRoute: typeof AuthenticatedCarregadoresClientesIndexRouteImport
      parentRoute: typeof AuthenticatedCarregadoresClientesRoute
    }
    '/_authenticated/admin/logs/': {
      id: '/_authenticated/admin/logs/'
      path: '/admin/logs'
      fullPath: '/admin/logs/'
      preLoaderRoute: typeof AuthenticatedAdminLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sap-nfs': {
      id: '/api/public/hooks/sap-nfs'
      path: '/api/public/hooks/sap-nfs'
      fullPath: '/api/public/hooks/sap-nfs'
      preLoaderRoute: typeof ApiPublicHooksSapNfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/pix-itau': {
      id: '/api/public/hooks/pix-itau'
      path: '/api/public/hooks/pix-itau'
      fullPath: '/api/public/hooks/pix-itau'
      preLoaderRoute: typeof ApiPublicHooksPixItauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/pagamento-link': {
      id: '/api/public/hooks/pagamento-link'
      path: '/api/public/hooks/pagamento-link'
      fullPath: '/api/public/hooks/pagamento-link'
      preLoaderRoute: typeof ApiPublicHooksPagamentoLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/fretefy-tracking': {
      id: '/api/public/hooks/fretefy-tracking'
      path: '/api/public/hooks/fretefy-tracking'
      fullPath: '/api/public/hooks/fretefy-tracking'
      preLoaderRoute: typeof ApiPublicHooksFretefyTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/solar/propostas/nova': {
      id: '/_authenticated/solar/propostas/nova'
      path: '/solar/propostas/nova'
      fullPath: '/solar/propostas/nova'
      preLoaderRoute: typeof AuthenticatedSolarPropostasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solar/dashboards/metas': {
      id: '/_authenticated/solar/dashboards/metas'
      path: '/metas'
      fullPath: '/solar/dashboards/metas'
      preLoaderRoute: typeof AuthenticatedSolarDashboardsMetasRouteImport
      parentRoute: typeof AuthenticatedSolarDashboardsRoute
    }
    '/_authenticated/solar/clientes/sugestoes': {
      id: '/_authenticated/solar/clientes/sugestoes'
      path: '/sugestoes'
      fullPath: '/solar/clientes/sugestoes'
      preLoaderRoute: typeof AuthenticatedSolarClientesSugestoesRouteImport
      parentRoute: typeof AuthenticatedSolarClientesRoute
    }
    '/_authenticated/solar/clientes/segmentacao': {
      id: '/_authenticated/solar/clientes/segmentacao'
      path: '/segmentacao'
      fullPath: '/solar/clientes/segmentacao'
      preLoaderRoute: typeof AuthenticatedSolarClientesSegmentacaoRouteImport
      parentRoute: typeof AuthenticatedSolarClientesRoute
    }
    '/_authenticated/solar/clientes/ranking': {
      id: '/_authenticated/solar/clientes/ranking'
      path: '/ranking'
      fullPath: '/solar/clientes/ranking'
      preLoaderRoute: typeof AuthenticatedSolarClientesRankingRouteImport
      parentRoute: typeof AuthenticatedSolarClientesRoute
    }
    '/_authenticated/solar/clientes/perfil': {
      id: '/_authenticated/solar/clientes/perfil'
      path: '/perfil'
      fullPath: '/solar/clientes/perfil'
      preLoaderRoute: typeof AuthenticatedSolarClientesPerfilRouteImport
      parentRoute: typeof AuthenticatedSolarClientesRoute
    }
    '/_authenticated/solar/clientes/cadastros': {
      id: '/_authenticated/solar/clientes/cadastros'
      path: '/cadastros'
      fullPath: '/solar/clientes/cadastros'
      preLoaderRoute: typeof AuthenticatedSolarClientesCadastrosRouteImport
      parentRoute: typeof AuthenticatedSolarClientesRoute
    }
    '/_authenticated/carregadores/propostas/visualizar': {
      id: '/_authenticated/carregadores/propostas/visualizar'
      path: '/visualizar'
      fullPath: '/carregadores/propostas/visualizar'
      preLoaderRoute: typeof AuthenticatedCarregadoresPropostasVisualizarRouteImport
      parentRoute: typeof AuthenticatedCarregadoresPropostasRoute
    }
    '/_authenticated/carregadores/propostas/nova': {
      id: '/_authenticated/carregadores/propostas/nova'
      path: '/nova'
      fullPath: '/carregadores/propostas/nova'
      preLoaderRoute: typeof AuthenticatedCarregadoresPropostasNovaRouteImport
      parentRoute: typeof AuthenticatedCarregadoresPropostasRoute
    }
    '/_authenticated/carregadores/propostas/auditoria': {
      id: '/_authenticated/carregadores/propostas/auditoria'
      path: '/auditoria'
      fullPath: '/carregadores/propostas/auditoria'
      preLoaderRoute: typeof AuthenticatedCarregadoresPropostasAuditoriaRouteImport
      parentRoute: typeof AuthenticatedCarregadoresPropostasRoute
    }
    '/_authenticated/carregadores/clientes/cadastros': {
      id: '/_authenticated/carregadores/clientes/cadastros'
      path: '/cadastros'
      fullPath: '/carregadores/clientes/cadastros'
      preLoaderRoute: typeof AuthenticatedCarregadoresClientesCadastrosRouteImport
      parentRoute: typeof AuthenticatedCarregadoresClientesRoute
    }
    '/_authenticated/admin/logs/retencao': {
      id: '/_authenticated/admin/logs/retencao'
      path: '/admin/logs/retencao'
      fullPath: '/admin/logs/retencao'
      preLoaderRoute: typeof AuthenticatedAdminLogsRetencaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/logs/moderacao': {
      id: '/_authenticated/admin/logs/moderacao'
      path: '/admin/logs/moderacao'
      fullPath: '/admin/logs/moderacao'
      preLoaderRoute: typeof AuthenticatedAdminLogsModeracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/logs/integracoes': {
      id: '/_authenticated/admin/logs/integracoes'
      path: '/admin/logs/integracoes'
      fullPath: '/admin/logs/integracoes'
      preLoaderRoute: typeof AuthenticatedAdminLogsIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/logs/gatilhos': {
      id: '/_authenticated/admin/logs/gatilhos'
      path: '/admin/logs/gatilhos'
      fullPath: '/admin/logs/gatilhos'
      preLoaderRoute: typeof AuthenticatedAdminLogsGatilhosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/integracoes_/$slug': {
      id: '/_authenticated/admin/integracoes_/$slug'
      path: '/admin/integracoes/$slug'
      fullPath: '/admin/integracoes/$slug'
      preLoaderRoute: typeof AuthenticatedAdminIntegracoesSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/pix-itau/$': {
      id: '/api/public/hooks/pix-itau/$'
      path: '/$'
      fullPath: '/api/public/hooks/pix-itau/$'
      preLoaderRoute: typeof ApiPublicHooksPixItauSplatRouteImport
      parentRoute: typeof ApiPublicHooksPixItauRoute
    }
  }
}

interface AuthenticatedMarketingRouteChildren {
  AuthenticatedMarketingCacRoute: typeof AuthenticatedMarketingCacRoute
  AuthenticatedMarketingCohortRoute: typeof AuthenticatedMarketingCohortRoute
  AuthenticatedMarketingGargaloRoute: typeof AuthenticatedMarketingGargaloRoute
  AuthenticatedMarketingMetasRoute: typeof AuthenticatedMarketingMetasRoute
  AuthenticatedMarketingPreVendasRoute: typeof AuthenticatedMarketingPreVendasRoute
  AuthenticatedMarketingSocialRoute: typeof AuthenticatedMarketingSocialRoute
  AuthenticatedMarketingTrafegoRoute: typeof AuthenticatedMarketingTrafegoRoute
  AuthenticatedMarketingIndexRoute: typeof AuthenticatedMarketingIndexRoute
}

const AuthenticatedMarketingRouteChildren: AuthenticatedMarketingRouteChildren =
  {
    AuthenticatedMarketingCacRoute: AuthenticatedMarketingCacRoute,
    AuthenticatedMarketingCohortRoute: AuthenticatedMarketingCohortRoute,
    AuthenticatedMarketingGargaloRoute: AuthenticatedMarketingGargaloRoute,
    AuthenticatedMarketingMetasRoute: AuthenticatedMarketingMetasRoute,
    AuthenticatedMarketingPreVendasRoute: AuthenticatedMarketingPreVendasRoute,
    AuthenticatedMarketingSocialRoute: AuthenticatedMarketingSocialRoute,
    AuthenticatedMarketingTrafegoRoute: AuthenticatedMarketingTrafegoRoute,
    AuthenticatedMarketingIndexRoute: AuthenticatedMarketingIndexRoute,
  }

const AuthenticatedMarketingRouteWithChildren =
  AuthenticatedMarketingRoute._addFileChildren(
    AuthenticatedMarketingRouteChildren,
  )

interface AuthenticatedCarregadoresClientesRouteChildren {
  AuthenticatedCarregadoresClientesCadastrosRoute: typeof AuthenticatedCarregadoresClientesCadastrosRoute
  AuthenticatedCarregadoresClientesIndexRoute: typeof AuthenticatedCarregadoresClientesIndexRoute
}

const AuthenticatedCarregadoresClientesRouteChildren: AuthenticatedCarregadoresClientesRouteChildren =
  {
    AuthenticatedCarregadoresClientesCadastrosRoute:
      AuthenticatedCarregadoresClientesCadastrosRoute,
    AuthenticatedCarregadoresClientesIndexRoute:
      AuthenticatedCarregadoresClientesIndexRoute,
  }

const AuthenticatedCarregadoresClientesRouteWithChildren =
  AuthenticatedCarregadoresClientesRoute._addFileChildren(
    AuthenticatedCarregadoresClientesRouteChildren,
  )

interface AuthenticatedCarregadoresPropostasRouteChildren {
  AuthenticatedCarregadoresPropostasAuditoriaRoute: typeof AuthenticatedCarregadoresPropostasAuditoriaRoute
  AuthenticatedCarregadoresPropostasNovaRoute: typeof AuthenticatedCarregadoresPropostasNovaRoute
  AuthenticatedCarregadoresPropostasVisualizarRoute: typeof AuthenticatedCarregadoresPropostasVisualizarRoute
  AuthenticatedCarregadoresPropostasIndexRoute: typeof AuthenticatedCarregadoresPropostasIndexRoute
}

const AuthenticatedCarregadoresPropostasRouteChildren: AuthenticatedCarregadoresPropostasRouteChildren =
  {
    AuthenticatedCarregadoresPropostasAuditoriaRoute:
      AuthenticatedCarregadoresPropostasAuditoriaRoute,
    AuthenticatedCarregadoresPropostasNovaRoute:
      AuthenticatedCarregadoresPropostasNovaRoute,
    AuthenticatedCarregadoresPropostasVisualizarRoute:
      AuthenticatedCarregadoresPropostasVisualizarRoute,
    AuthenticatedCarregadoresPropostasIndexRoute:
      AuthenticatedCarregadoresPropostasIndexRoute,
  }

const AuthenticatedCarregadoresPropostasRouteWithChildren =
  AuthenticatedCarregadoresPropostasRoute._addFileChildren(
    AuthenticatedCarregadoresPropostasRouteChildren,
  )

interface AuthenticatedSolarClientesRouteChildren {
  AuthenticatedSolarClientesCadastrosRoute: typeof AuthenticatedSolarClientesCadastrosRoute
  AuthenticatedSolarClientesPerfilRoute: typeof AuthenticatedSolarClientesPerfilRoute
  AuthenticatedSolarClientesRankingRoute: typeof AuthenticatedSolarClientesRankingRoute
  AuthenticatedSolarClientesSegmentacaoRoute: typeof AuthenticatedSolarClientesSegmentacaoRoute
  AuthenticatedSolarClientesSugestoesRoute: typeof AuthenticatedSolarClientesSugestoesRoute
}

const AuthenticatedSolarClientesRouteChildren: AuthenticatedSolarClientesRouteChildren =
  {
    AuthenticatedSolarClientesCadastrosRoute:
      AuthenticatedSolarClientesCadastrosRoute,
    AuthenticatedSolarClientesPerfilRoute:
      AuthenticatedSolarClientesPerfilRoute,
    AuthenticatedSolarClientesRankingRoute:
      AuthenticatedSolarClientesRankingRoute,
    AuthenticatedSolarClientesSegmentacaoRoute:
      AuthenticatedSolarClientesSegmentacaoRoute,
    AuthenticatedSolarClientesSugestoesRoute:
      AuthenticatedSolarClientesSugestoesRoute,
  }

const AuthenticatedSolarClientesRouteWithChildren =
  AuthenticatedSolarClientesRoute._addFileChildren(
    AuthenticatedSolarClientesRouteChildren,
  )

interface AuthenticatedSolarDashboardsRouteChildren {
  AuthenticatedSolarDashboardsMetasRoute: typeof AuthenticatedSolarDashboardsMetasRoute
}

const AuthenticatedSolarDashboardsRouteChildren: AuthenticatedSolarDashboardsRouteChildren =
  {
    AuthenticatedSolarDashboardsMetasRoute:
      AuthenticatedSolarDashboardsMetasRoute,
  }

const AuthenticatedSolarDashboardsRouteWithChildren =
  AuthenticatedSolarDashboardsRoute._addFileChildren(
    AuthenticatedSolarDashboardsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminAtividadeRoute: typeof AuthenticatedAdminAtividadeRoute
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminComissoesRoute: typeof AuthenticatedAdminComissoesRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminEstoqueRoute: typeof AuthenticatedAdminEstoqueRoute
  AuthenticatedAdminFreteRegrasRoute: typeof AuthenticatedAdminFreteRegrasRoute
  AuthenticatedAdminIntegracoesRoute: typeof AuthenticatedAdminIntegracoesRoute
  AuthenticatedAdminMetasRoute: typeof AuthenticatedAdminMetasRoute
  AuthenticatedAdminModeracaoRoute: typeof AuthenticatedAdminModeracaoRoute
  AuthenticatedAdminModulosSolarRoute: typeof AuthenticatedAdminModulosSolarRoute
  AuthenticatedAdminPerfisRoute: typeof AuthenticatedAdminPerfisRoute
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRoute
  AuthenticatedAdminProdutosSolarRoute: typeof AuthenticatedAdminProdutosSolarRoute
  AuthenticatedAdminRegrasRoute: typeof AuthenticatedAdminRegrasRoute
  AuthenticatedAdminTabelasRoute: typeof AuthenticatedAdminTabelasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminVinculosRoute: typeof AuthenticatedAdminVinculosRoute
  AuthenticatedCarregadoresClientesRoute: typeof AuthenticatedCarregadoresClientesRouteWithChildren
  AuthenticatedCarregadoresComissoesRoute: typeof AuthenticatedCarregadoresComissoesRoute
  AuthenticatedCarregadoresFreteRegrasRoute: typeof AuthenticatedCarregadoresFreteRegrasRoute
  AuthenticatedCarregadoresMetasRoute: typeof AuthenticatedCarregadoresMetasRoute
  AuthenticatedCarregadoresPedidosRoute: typeof AuthenticatedCarregadoresPedidosRoute
  AuthenticatedCarregadoresProdutosRoute: typeof AuthenticatedCarregadoresProdutosRoute
  AuthenticatedCarregadoresPropostasRoute: typeof AuthenticatedCarregadoresPropostasRouteWithChildren
  AuthenticatedCarregadoresRegrasRoute: typeof AuthenticatedCarregadoresRegrasRoute
  AuthenticatedCarregadoresTarefasRoute: typeof AuthenticatedCarregadoresTarefasRoute
  AuthenticatedSolarAtlasRoute: typeof AuthenticatedSolarAtlasRoute
  AuthenticatedSolarClientesRoute: typeof AuthenticatedSolarClientesRouteWithChildren
  AuthenticatedSolarCuponsRoute: typeof AuthenticatedSolarCuponsRoute
  AuthenticatedSolarDashboardsRoute: typeof AuthenticatedSolarDashboardsRouteWithChildren
  AuthenticatedSolarPedidosRoute: typeof AuthenticatedSolarPedidosRoute
  AuthenticatedSolarTarefasRoute: typeof AuthenticatedSolarTarefasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedCarregadoresIndexRoute: typeof AuthenticatedCarregadoresIndexRoute
  AuthenticatedAdminIntegracoesSlugRoute: typeof AuthenticatedAdminIntegracoesSlugRoute
  AuthenticatedAdminLogsGatilhosRoute: typeof AuthenticatedAdminLogsGatilhosRoute
  AuthenticatedAdminLogsIntegracoesRoute: typeof AuthenticatedAdminLogsIntegracoesRoute
  AuthenticatedAdminLogsModeracaoRoute: typeof AuthenticatedAdminLogsModeracaoRoute
  AuthenticatedAdminLogsRetencaoRoute: typeof AuthenticatedAdminLogsRetencaoRoute
  AuthenticatedSolarPropostasNovaRoute: typeof AuthenticatedSolarPropostasNovaRoute
  AuthenticatedAdminLogsIndexRoute: typeof AuthenticatedAdminLogsIndexRoute
  AuthenticatedSolarPropostasIndexRoute: typeof AuthenticatedSolarPropostasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMarketingRoute: AuthenticatedMarketingRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminAtividadeRoute: AuthenticatedAdminAtividadeRoute,
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminComissoesRoute: AuthenticatedAdminComissoesRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminEstoqueRoute: AuthenticatedAdminEstoqueRoute,
  AuthenticatedAdminFreteRegrasRoute: AuthenticatedAdminFreteRegrasRoute,
  AuthenticatedAdminIntegracoesRoute: AuthenticatedAdminIntegracoesRoute,
  AuthenticatedAdminMetasRoute: AuthenticatedAdminMetasRoute,
  AuthenticatedAdminModeracaoRoute: AuthenticatedAdminModeracaoRoute,
  AuthenticatedAdminModulosSolarRoute: AuthenticatedAdminModulosSolarRoute,
  AuthenticatedAdminPerfisRoute: AuthenticatedAdminPerfisRoute,
  AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRoute,
  AuthenticatedAdminProdutosSolarRoute: AuthenticatedAdminProdutosSolarRoute,
  AuthenticatedAdminRegrasRoute: AuthenticatedAdminRegrasRoute,
  AuthenticatedAdminTabelasRoute: AuthenticatedAdminTabelasRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminVinculosRoute: AuthenticatedAdminVinculosRoute,
  AuthenticatedCarregadoresClientesRoute:
    AuthenticatedCarregadoresClientesRouteWithChildren,
  AuthenticatedCarregadoresComissoesRoute:
    AuthenticatedCarregadoresComissoesRoute,
  AuthenticatedCarregadoresFreteRegrasRoute:
    AuthenticatedCarregadoresFreteRegrasRoute,
  AuthenticatedCarregadoresMetasRoute: AuthenticatedCarregadoresMetasRoute,
  AuthenticatedCarregadoresPedidosRoute: AuthenticatedCarregadoresPedidosRoute,
  AuthenticatedCarregadoresProdutosRoute:
    AuthenticatedCarregadoresProdutosRoute,
  AuthenticatedCarregadoresPropostasRoute:
    AuthenticatedCarregadoresPropostasRouteWithChildren,
  AuthenticatedCarregadoresRegrasRoute: AuthenticatedCarregadoresRegrasRoute,
  AuthenticatedCarregadoresTarefasRoute: AuthenticatedCarregadoresTarefasRoute,
  AuthenticatedSolarAtlasRoute: AuthenticatedSolarAtlasRoute,
  AuthenticatedSolarClientesRoute: AuthenticatedSolarClientesRouteWithChildren,
  AuthenticatedSolarCuponsRoute: AuthenticatedSolarCuponsRoute,
  AuthenticatedSolarDashboardsRoute:
    AuthenticatedSolarDashboardsRouteWithChildren,
  AuthenticatedSolarPedidosRoute: AuthenticatedSolarPedidosRoute,
  AuthenticatedSolarTarefasRoute: AuthenticatedSolarTarefasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedCarregadoresIndexRoute: AuthenticatedCarregadoresIndexRoute,
  AuthenticatedAdminIntegracoesSlugRoute:
    AuthenticatedAdminIntegracoesSlugRoute,
  AuthenticatedAdminLogsGatilhosRoute: AuthenticatedAdminLogsGatilhosRoute,
  AuthenticatedAdminLogsIntegracoesRoute:
    AuthenticatedAdminLogsIntegracoesRoute,
  AuthenticatedAdminLogsModeracaoRoute: AuthenticatedAdminLogsModeracaoRoute,
  AuthenticatedAdminLogsRetencaoRoute: AuthenticatedAdminLogsRetencaoRoute,
  AuthenticatedSolarPropostasNovaRoute: AuthenticatedSolarPropostasNovaRoute,
  AuthenticatedAdminLogsIndexRoute: AuthenticatedAdminLogsIndexRoute,
  AuthenticatedSolarPropostasIndexRoute: AuthenticatedSolarPropostasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicHooksPixItauRouteChildren {
  ApiPublicHooksPixItauSplatRoute: typeof ApiPublicHooksPixItauSplatRoute
}

const ApiPublicHooksPixItauRouteChildren: ApiPublicHooksPixItauRouteChildren = {
  ApiPublicHooksPixItauSplatRoute: ApiPublicHooksPixItauSplatRoute,
}

const ApiPublicHooksPixItauRouteWithChildren =
  ApiPublicHooksPixItauRoute._addFileChildren(
    ApiPublicHooksPixItauRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TvGeralRoute: TvGeralRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicAppVersionRoute: ApiPublicAppVersionRoute,
  ApiPublicHooksFretefyTrackingRoute: ApiPublicHooksFretefyTrackingRoute,
  ApiPublicHooksPagamentoLinkRoute: ApiPublicHooksPagamentoLinkRoute,
  ApiPublicHooksPixItauRoute: ApiPublicHooksPixItauRouteWithChildren,
  ApiPublicHooksSapNfsRoute: ApiPublicHooksSapNfsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
